import type { GameCategory, GameMeta } from './types'

export const GAME_OPTIONS: Record<string, Array<{ key: string; label: string; description: string; default: boolean }>> = {
  'hearts': [
    { key: 'shootTheMoon', label: 'Shoot the moon', description: 'Getting all hearts + Spar dame gives everyone else 240 pts', default: true },
  ],
}

export const CATEGORIES: { id: GameCategory; label: string; icon: string }[] = [
  { id: 'dice',    label: 'Dice Games',    icon: '🎲' },
  { id: 'card',    label: 'Card Games',    icon: '🃏' },
  { id: 'darts',   label: 'Darts',         icon: '🎯' },
  { id: 'board',   label: 'Board Games',   icon: '♟️' },
  { id: 'outdoor', label: 'Outdoor',       icon: '🌿' },
  { id: 'party',   label: 'Party Games',   icon: '🎉' },
  { id: 'sport',   label: 'Sport & 1v1',   icon: '🏓' },
  { id: 'puzzle',  label: 'Puzzle Games',  icon: '🧩' },
]

export const GAMES: GameMeta[] = [
  { id: 'qwixx',        name: 'Qwixx',             name_alt: null,   category: 'dice', description: 'Roll six dice and cross off numbers in four colour rows. Lock a row or score big — but blocking others costs everyone.',             min_players: 2, max_players: 5, higher_is_better: true,  active: true, sort_order: 6,  icon: '🎲' },
  { id: 'king-of-tokyo', name: 'King of Tokyo',  name_alt: null,   category: 'dice', description: 'Roll custom dice to stomp Tokyo, zap rivals, and grab victory points. First to 20 points or last monster standing wins.',                min_players: 2, max_players: 6, higher_is_better: true,  active: true, sort_order: 7,  icon: '👾' },
  { id: 'maxi-yatzy', name: 'Maxi Yatzy',      name_alt: 'Yatzy Maxi',         category: 'dice',   description: 'The classic dice game with 6 dice and expanded categories including House, Tower, and Maxi Yatzy bonus.',                          min_players: 2, max_players: 8, higher_is_better: true,  active: true,  sort_order: 1,  icon: '🎲' },
  { id: 'yatzy',      name: 'Yatzy',            name_alt: 'Yahtzee',            category: 'dice',   description: 'The original 5-dice version. Score in 15 categories and earn a 50-point bonus for 63+ in the upper section.',                     min_players: 2, max_players: 8, higher_is_better: true,  active: true,  sort_order: 2,  icon: '🎲' },
  { id: 'darts-501',  name: 'Darts 501',        name_alt: 'Darts',              category: 'darts',  description: 'Start at 501, count down to exactly zero. Must finish on a double. First to zero wins.',                                         min_players: 2, max_players: 8, higher_is_better: false, active: true,  sort_order: 3,  icon: '🎯' },
  { id: 'hearts',     name: 'Hearts',           name_alt: 'Spardam',            category: 'card',   description: 'Avoid taking hearts and the Queen of Spades. Hearts 10pts, Ace 20pts, Spar dame 100pts, Ruter knekt −100pts. Lowest score wins.', min_players: 3, max_players: 6, higher_is_better: false, active: true,  sort_order: 4,  icon: '♥️' },
  { id: 'farkle',     name: 'Farkle / 10 000',  name_alt: '10 000',             category: 'dice',   description: 'Roll dice, score points, and decide when to bank or risk it all. First to reach 10 000 points wins.',                            min_players: 2, max_players: 8, higher_is_better: true,  active: true,  sort_order: 5,  icon: '🎲' },
  { id: 'poker',      name: 'Texas Hold\'em',   name_alt: 'Poker',              category: 'card',   description: 'Tournament clock with blind structure, break timer, chip count leaderboard and player elimination. Great for home tournaments.', min_players: 2, max_players: 100, higher_is_better: true, active: true, sort_order: 6, icon: '🃏' },
  { id: 'spades',     name: 'Spades',           name_alt: null,                 category: 'card',   description: 'Bid on tricks and score points for making your bid. Spades are always trump.',                                                    min_players: 4, max_players: 4, higher_is_better: true,  active: true,  sort_order: 10, icon: '♠️' },
  { id: 'rummy',      name: 'Rummy',            name_alt: 'Remi',               category: 'card',   description: 'Form sets and runs to empty your hand before your opponents.',                                                                    min_players: 2, max_players: 6, higher_is_better: false, active: true,  sort_order: 11, icon: '🃏' },
  { id: 'gin-rummy',  name: 'Gin Rummy',        name_alt: null,                 category: 'card',   description: 'Two-player rummy with knocking and gin bonuses.',                                                                                 min_players: 2, max_players: 2, higher_is_better: false, active: true,  sort_order: 12, icon: '🃏' },
  { id: 'canasta',    name: 'Canasta',          name_alt: null,                 category: 'card',   description: 'Form melds of seven cards to score points. First to 5000 wins.',                                                                  min_players: 2, max_players: 6, higher_is_better: true,  active: true,  sort_order: 13, icon: '🃏' },
  { id: 'phase-10',   name: 'Phase 10',         name_alt: null,                 category: 'card',   description: 'Complete 10 phases of specific card combinations before your opponents.',                                                         min_players: 2, max_players: 6, higher_is_better: false, active: true,  sort_order: 14, icon: '🃏' },
  { id: 'uno',        name: 'UNO',              name_alt: null,                 category: 'card',   description: 'Track penalty points across rounds — lowest score when someone reaches 500 wins.',                                                min_players: 2, max_players: 10, higher_is_better: false, active: true,  sort_order: 15, icon: '🃏' },
  { id: 'cabo',       name: 'Cabo',             name_alt: null,                 category: 'card',   description: 'Know your cards, minimise your score, and call Cabo at the right time.',                                                          min_players: 2, max_players: 8, higher_is_better: false, active: true,  sort_order: 16, icon: '🃏' },
  { id: 'cribbage',   name: 'Cribbage',         name_alt: null,                 category: 'card',   description: 'Score points through combinations and pegging in this classic two-player game.',                                                  min_players: 2, max_players: 4, higher_is_better: true,  active: true,  sort_order: 17, icon: '🃏' },
  { id: 'doppelkopf', name: 'Doppelkopf',       name_alt: null,                 category: 'card',   description: 'Popular German trick-taking game for exactly 4 players with complex trump rules.',                                                min_players: 4, max_players: 4, higher_is_better: true,  active: true,  sort_order: 18, icon: '🃏' },
  { id: 'skat',       name: 'Skat',             name_alt: null,                 category: 'card',   description: 'Competitive German card game with bidding and trump for exactly 3 players.',                                                      min_players: 3, max_players: 3, higher_is_better: true,  active: true,  sort_order: 19, icon: '🃏' },
  { id: 'darts-cricket', name: 'Darts Cricket', name_alt: null,                 category: 'darts',  description: 'Close numbers 15–20 and the bullseye before your opponent.',                                                                     min_players: 2, max_players: 6, higher_is_better: true,  active: true,  sort_order: 20, icon: '🎯' },
  { id: 'darts-301',  name: 'Darts 301',        name_alt: null,                 category: 'darts',  description: 'Like 501 but starting from 301. Must finish on a double.',                                                                       min_players: 2, max_players: 8, higher_is_better: false, active: true,  sort_order: 21, icon: '🎯' },
  { id: 'catan',           name: 'Catan',             name_alt: 'Settlers of Catan', category: 'board', description: 'Build settlements, cities, and roads to reach 10 victory points first.',                                                                    min_players: 3, max_players: 4, higher_is_better: true, active: true, sort_order: 30, icon: '🏘️' },
  { id: 'ticket-to-ride', name: 'Ticket to Ride',    name_alt: null,                category: 'board', description: 'Claim railway routes across the map to complete destination tickets.',                                                                         min_players: 2, max_players: 5, higher_is_better: true, active: true, sort_order: 31, icon: '🚂' },
  { id: 'carcassonne',    name: 'Carcassonne',        name_alt: null,                category: 'board', description: 'Build the medieval landscape tile by tile, scoring cities, roads, and monasteries.',                                                          min_players: 2, max_players: 5, higher_is_better: true, active: true, sort_order: 32, icon: '🏰' },
  { id: 'scrabble',       name: 'Scrabble',           name_alt: null,                category: 'board', description: 'Score points by placing words on the board, using high-value letters strategically.',                                                         min_players: 2, max_players: 4, higher_is_better: true, active: true, sort_order: 33, icon: '🔤' },
  { id: 'backgammon',     name: 'Backgammon',         name_alt: null,                category: 'board', description: 'Race your pieces home and bear them off before your opponent.',                                                                                min_players: 2, max_players: 2, higher_is_better: true, active: true, sort_order: 34, icon: '🎲' },
  { id: 'sequence',       name: 'Sequence',           name_alt: null,                category: 'board', description: 'Play cards to place chips on the board and form sequences of five.',                                                                          min_players: 2, max_players: 12, higher_is_better: true, active: true, sort_order: 35, icon: '🃏' },
  { id: 'everdell',       name: 'Everdell',           name_alt: null,                category: 'board', description: 'Build a city of critters and constructions in an enchanting forest. Score points from buildings, events, and end-game bonuses.',              min_players: 1, max_players: 4, higher_is_better: true, active: true, sort_order: 36, icon: '🐿️' },
  { id: 'wingspan',       name: 'Wingspan',           name_alt: null,                category: 'board', description: 'Attract birds to your wildlife preserve. Score points from bird cards, eggs, cached food, and end-of-round goals.',                           min_players: 1, max_players: 5, higher_is_better: true, active: true, sort_order: 37, icon: '🦅' },
  { id: '7-wonders',      name: '7 Wonders',          name_alt: null,                category: 'board', description: 'Draft cards over three ages to build your ancient civilization. Most victory points from science, military, and wonders wins.',                min_players: 2, max_players: 7, higher_is_better: true, active: true, sort_order: 38, icon: '🏛️' },
  { id: 'azul',           name: 'Azul',               name_alt: null,                category: 'board', description: 'Draft colourful tiles to decorate your palace wall. Score for completed rows, columns, and sets — avoid leftover tiles.',                     min_players: 2, max_players: 4, higher_is_better: true, active: true, sort_order: 39, icon: '🔷' },
  { id: 'splendor',       name: 'Splendor',           name_alt: null,                category: 'board', description: 'Collect gem tokens to buy development cards and attract nobles. First to 15 prestige points wins.',                                           min_players: 2, max_players: 4, higher_is_better: true, active: true, sort_order: 40, icon: '💎' },
  { id: 'terraforming-mars', name: 'Terraforming Mars', name_alt: null,             category: 'board', description: 'Compete to terraform Mars by raising temperature, oxygen, and oceans. Most Terraform Rating and victory points wins.',                        min_players: 1, max_players: 5, higher_is_better: true, active: true, sort_order: 41, icon: '🪐' },
  { id: 'pandemic',       name: 'Pandemic',           name_alt: null,                category: 'board', description: 'Work together to cure four diseases before outbreaks spiral out of control. Track how many rounds you survive or diseases you cure.',          min_players: 2, max_players: 4, higher_is_better: true, active: true, sort_order: 42, icon: '🦠' },
  { id: 'petanque',   name: 'Pétanque / Boule', name_alt: 'Boule',              category: 'outdoor', description: 'Throw metal balls to get closest to the jack. Most points after agreed rounds wins.',                                           min_players: 2, max_players: 8, higher_is_better: true,  active: true,  sort_order: 40, icon: '🎳' },
  { id: 'bowling',    name: 'Bowling',          name_alt: null,                 category: 'outdoor', description: 'Track your bowling scores including strikes, spares, and frames.',                                                               min_players: 1, max_players: 8, higher_is_better: true,  active: true,  sort_order: 41, icon: '🎳' },
  { id: 'croquet',    name: 'Croquet',          name_alt: null,                 category: 'outdoor', description: 'Track points as players hit balls through hoops in the correct order.',                                                          min_players: 2, max_players: 6, higher_is_better: true,  active: true,  sort_order: 42, icon: '🔨' },
  { id: 'table-tennis', name: 'Bordtennis',      name_alt: 'Ping Pong',       category: 'sport',  description: 'Track sets and games of table tennis. Best of 3 or 5 sets — most sets won wins.',                                             min_players: 2, max_players: 4, higher_is_better: true,  active: true,  sort_order: 50, icon: '🏓' },
  { id: 'billiards',   name: 'Biljard',          name_alt: 'Pool',            category: 'sport',  description: 'Track frames of pool or billiards. Most frames won wins the match.',                                                            min_players: 2, max_players: 4, higher_is_better: true,  active: true,  sort_order: 51, icon: '🎱' },
  { id: 'badminton',   name: 'Badminton',         name_alt: null,              category: 'sport',  description: 'Track sets of badminton. First to win 2 sets (best of 3) wins the match.',                                                     min_players: 2, max_players: 4, higher_is_better: true,  active: true,  sort_order: 52, icon: '🏸' },
  { id: 'foosball',    name: 'Fotballbord',        name_alt: 'Foosball',        category: 'sport',  description: 'Track goals scored in table football. Most goals or most games won wins.',                                                     min_players: 2, max_players: 4, higher_is_better: true,  active: true,  sort_order: 53, icon: '⚽' },
  { id: 'kubb',       name: 'Kubb',             name_alt: 'Vikingkubb',         category: 'outdoor', description: 'Knock over the opponent\'s kubbs with batons, then topple the king to win.',                                                     min_players: 2, max_players: 12, higher_is_better: true,  active: true,  sort_order: 43, icon: '🪵' },
  { id: 'molkky',     name: 'Mölkky',           name_alt: null,                 category: 'outdoor', description: 'Throw the skittle to knock over numbered pins. First to reach exactly 50 points wins.',                                         min_players: 2, max_players: 12, higher_is_better: true,  active: true,  sort_order: 44, icon: '🎯' },
  { id: 'disc-golf',  name: 'Disc Golf',        name_alt: 'Frisbeegolf',        category: 'outdoor', description: 'Throw discs into basket goals in as few throws as possible. Lowest score wins.',                                                 min_players: 1, max_players: 8, higher_is_better: false, active: true,  sort_order: 45, icon: '🥏' },
  { id: 'cornhole',   name: 'Cornhole',         name_alt: 'Bønneposs',          category: 'outdoor', description: 'Toss bags into a hole for 3 pts or land on the board for 1 pt. Cancel scoring. First to 21 wins.',                              min_players: 2, max_players: 4, higher_is_better: true,  active: true,  sort_order: 46, icon: '🎯' },
  { id: 'golf',       name: 'Golf',             name_alt: null,                 category: 'outdoor', description: 'Set up your course hole by hole with par values. Track strokes per hole and see your score vs par in real time.',               min_players: 1, max_players: 8, higher_is_better: false, active: true,  sort_order: 47, icon: '⛳' },
  { id: 'tennis',     name: 'Tennis',           name_alt: null,                 category: 'outdoor', description: 'Track sets in a tennis match. Enter who won each set and the score. Works for singles and doubles.',                             min_players: 2, max_players: 4, higher_is_better: true,  active: true,  sort_order: 48, icon: '🎾' },
  { id: 'sudoku',     name: 'Sudoku',           name_alt: null,                 category: 'puzzle', description: 'Solve the 9×9 puzzle as fast as you can. Everyone gets the same board — lowest time wins.',                                             min_players: 1, max_players: 8,  higher_is_better: false, active: true,  sort_order: 70, icon: '🔢' },
  { id: 'beer-pong',  name: 'Beer Pong',        name_alt: null,                 category: 'party',  description: 'Toss ping-pong balls into the opponent\'s cups. Hit a cup — they drink and it\'s removed. First to clear all cups wins.',         min_players: 2, max_players: 2, higher_is_better: true,  active: true,  sort_order: 60, icon: '🍺' },
  { id: 'bezzerwizzer', name: 'Bezzerwizzer',   name_alt: null,                 category: 'party',  description: 'Trivia-quiz der du velger kategori og stjeler poeng fra motstanderne. Legg inn poeng etter hver runde.',                          min_players: 2, max_players: 8, higher_is_better: true,  active: true,  sort_order: 61, icon: '🧠' },
  { id: 'alias',      name: 'Alias',            name_alt: null,                 category: 'party',  description: 'Forklar ord uten å si selve ordet. Lag konkurrerer om å gjette flest ord på tid. Legg inn poeng per runde.',                      min_players: 2, max_players: 12, higher_is_better: true, active: true,  sort_order: 62, icon: '💬' },
  { id: 'taboo',      name: 'Taboo',             name_alt: null,  category: 'party', description: 'Get your team to say the target word without using the five forbidden clue words. Most correct guesses per round wins.',            min_players: 4, max_players: 12, higher_is_better: true, active: true, sort_order: 64, icon: '🚫' },
  { id: 'pictionary', name: 'Pictionary',       name_alt: null,                 category: 'party',  description: 'Tegn ord så laget ditt gjetter. Poeng for riktig gjettet kort. Legg inn poeng per runde.',                                       min_players: 2, max_players: 12, higher_is_better: true, active: true,  sort_order: 63, icon: '🎨' },
]

export function getGame(id: string): GameMeta | undefined {
  return GAMES.find(g => g.id === id)
}

export function getGamesByCategory(category: GameCategory): GameMeta[] {
  return GAMES.filter(g => g.category === category).sort((a, b) => a.sort_order - b.sort_order)
}

export function getActiveGames(): GameMeta[] {
  return GAMES.filter(g => g.active).sort((a, b) => a.sort_order - b.sort_order)
}
