export interface GameRules {
  quickStart: string[]
  full: string[]
}

export const RULES: Record<string, GameRules> = {
  'maxi-yatzy': {
    quickStart: [
      'Roll 6 dice up to 3 times per turn, keeping any dice between rolls.',
      'Score in any empty category — each category can only be used once.',
      'Upper section (Ones–Sixes): score matching dice. Bonus of 100 pts if sum ≥ 84.',
      'Lower section: 1 Pair, 2 Pairs, 3 Pairs, 3/4/5 of a Kind, Straights, House (2+3), Full House (3+3), Tower (2+4), Chance, Maxi Yatzy (100 pts).',
      'Highest total score wins.',
    ],
    full: [
      'Each player takes turns rolling all 6 dice.',
      'After each roll you may set aside any dice and re-roll the rest — up to 3 rolls total.',
      'After your final roll, choose one unfilled category to score in.',
      'UPPER SECTION: Ones through Sixes — total the matching dice. Score 100 bonus if upper sum ≥ 84.',
      'LOWER SECTION:',
      '  1 Par: sum of highest pair',
      '  2 Par: sum of two pairs',
      '  3 Par: sum of three pairs',
      '  3 Like: sum of three matching dice',
      '  4 Like: sum of four matching dice',
      '  5 Like: sum of five matching dice',
      '  Liten Straight (1-2-3-4-5): 15 points',
      '  Stor Straight (2-3-4-5-6): 20 points',
      '  Full Straight (1-2-3-4-5-6): 21 points',
      '  House (2+3 of a kind): sum of all dice',
      '  Full House (3+3 of a kind): sum of all dice',
      '  Tower (2+4 of a kind): sum of all dice',
      '  Chance: sum of all dice',
      '  Maxi Yatzy (all 6 same): 100 points',
      'If you cannot or do not want to score a category, you must cross it out (score 0).',
      'Game ends when all players have filled every category. Highest total wins.',
    ],
  },
  'yatzy': {
    quickStart: [
      'Roll 5 dice up to 3 times per turn, keeping any dice between rolls.',
      'Score in any empty category — each can only be used once.',
      'Upper section (Ones–Sixes): score matching dice. Bonus of 50 pts if sum ≥ 63.',
      'Lower section: 1 Pair, 2 Pair, 3/4 of a Kind, Full House, Small/Large Straight, Chance, Yatzy (50 pts).',
      'Highest total wins.',
    ],
    full: [
      'Roll 5 dice up to 3 times per turn.',
      'After each roll you may keep any dice and re-roll the rest.',
      'Score in one unfilled category after your final roll.',
      'UPPER SECTION (Ones–Sixes): Score the total of all matching dice. 50 bonus points if upper section total ≥ 63.',
      'LOWER SECTION:',
      '  1 Pair: sum of highest pair',
      '  2 Pair: sum of two pairs',
      '  3 of a Kind: sum of three matching dice',
      '  4 of a Kind: sum of four matching dice',
      '  Full House (2+3): 25 points',
      '  Small Straight (1-2-3-4 or 2-3-4-5): 30 points',
      '  Large Straight (1-2-3-4-5 or 2-3-4-5-6): 40 points',
      '  Chance: sum of all 5 dice',
      '  Yatzy (all 5 same): 50 points',
      'Cross out any category you cannot or choose not to score (0 points).',
      'Game ends when all categories are filled. Highest total wins.',
    ],
  },
  'darts-501': {
    quickStart: [
      'Each player starts with 501 points.',
      'Take turns throwing 3 darts each. Subtract your score from your total.',
      'You must finish on exactly 0 — the finishing dart must land in a double (or bullseye).',
      'If you go below 0, or land exactly on 1, your turn is a "bust" — your score resets to what it was before your throw.',
      'First player to reach exactly 0 wins.',
    ],
    full: [
      'Each player begins with 501 points.',
      'Players alternate turns throwing 3 darts at the board.',
      'Score is the total of the 3 darts, subtracted from your current score.',
      'Doubles: doubles ring scores double the segment value.',
      'Trebles: treble ring scores triple the segment value.',
      'Bull: outer bull = 25, inner bull (bullseye) = 50.',
      'CHECKOUT: To win, you must reduce your score to exactly 0.',
      '  The final dart must land in a double or the bullseye.',
      '  If you cannot checkout or overshoot, your turn is a "bust" — score returns to start of that turn.',
      '  If your score reaches 1, it is a bust (cannot check out on 1).',
      'First player to reach exactly 0 wins.',
    ],
  },
  'hearts': {
    quickStart: [
      '3–6 players, standard 52-card deck (remove low cards to make it divide evenly).',
      'Each trick: highest card of the led suit wins. Hearts have no trump.',
      'SCORING: Hearts = 10 pts each (Ace of Hearts = 20 pts), Queen of Spades = 100 pts, Jack of Diamonds = −100 pts.',
      'Shooting the moon (optional): take ALL hearts + Queen of Spades → you score 0, everyone else gets 240 pts.',
      'Game ends when someone reaches 500 points. Lowest score wins.',
    ],
    full: [
      'Deal all cards evenly. Players pass 3 cards to the left before each round (direction rotates).',
      'The player with the 2 of Clubs leads the first trick.',
      'Players must follow suit if they can. If unable, play any card.',
      'The highest card of the led suit wins the trick. The winner leads next.',
      'Hearts cannot be led until a heart has been "broken" (played when unable to follow suit).',
      'SCORING PER ROUND:',
      '  Each heart = 10 penalty points',
      '  Ace of Hearts = 20 penalty points',
      '  Queen of Spades (Spar dame) = 100 penalty points',
      '  Jack of Diamonds (Ruter knekt) = −100 points',
      '  All other cards = 0',
      '  Total points distributed per round = 140',
      'SHOOTING THE MOON (optional rule):',
      '  If one player takes ALL hearts AND the Queen of Spades:',
      '  That player scores 0 for the round, all other players receive 240 points.',
      'Record running totals after each round.',
      'GAME END: The game ends after the round in which a player reaches or exceeds 500 points.',
      'The player with the LOWEST total score wins.',
    ],
  },
  'darts-301': {
    quickStart: [
      'Each player starts with 301 points.',
      'Take turns throwing 3 darts. Subtract your score from your total.',
      'You must finish on exactly 0 — the finishing dart must land in a double (or bullseye).',
      'If you bust (go below 0 or land on 1), your score resets to before your throw.',
      'First player to reach exactly 0 wins.',
    ],
    full: [
      'Same rules as 501, but starting from 301 — games are shorter and more intense.',
      'Each player begins with 301 points.',
      'Players alternate turns throwing 3 darts.',
      'Subtract your 3-dart total from your score each turn.',
      'To win, reduce your score to exactly 0. The final dart must land on a double or bullseye.',
      'Busting (going below 0 or hitting 1) cancels the entire turn — score returns to start of that turn.',
    ],
  },
  'darts-cricket': {
    quickStart: [
      'Numbers in play: 15, 16, 17, 18, 19, 20, and Bull.',
      'Hit a number 3 times to "close" it. Marks: 1 hit = /, 2 hits = X, 3 hits = closed (⊗).',
      'Once you\'ve closed a number, extra hits score points — but only if your opponent hasn\'t closed it too.',
      'Win by closing all numbers AND having the highest (or equal) score.',
    ],
    full: [
      'Numbers in play: 20, 19, 18, 17, 16, 15, and Bull (25/50).',
      'Each turn: throw 3 darts. Record marks on each number hit.',
      'Singles = 1 mark, doubles = 2 marks, triples = 3 marks. Outer bull = 1 mark, inner bull = 2 marks.',
      'Close a number by accumulating 3 marks on it.',
      'Scoring: if you close a number, extra marks score points (face value per mark), but only while at least one opponent hasn\'t closed it.',
      'Bull scores 25 pts per mark when scoring.',
      'WIN CONDITION: be the first to close all numbers AND have a score equal to or higher than all opponents.',
      'Strategy: close high-value numbers first to maximise scoring opportunities.',
    ],
  },
  'spades': {
    quickStart: [
      '4 players, 2 teams of 2 sitting opposite each other.',
      'Each player bids how many tricks they expect to take. Spades are always trump.',
      'Score 10 pts per trick bid if your team meets its bid. Overtricks (bags) score 1 pt each but 10 bags = −100 pts.',
      'Underbidding costs 10 pts per trick short.',
      'First team to 500 pts wins.',
    ],
    full: [
      'Deal all 52 cards (13 each). Players look at their cards and bid individually.',
      'Bids: estimate tricks you will take. Minimum bid is 1 (or Nil = 0, worth +100/−100).',
      'Team bid = sum of both partners\' bids.',
      'Spades are always trump. Lead any suit (except spades cannot lead until broken).',
      'Highest card of led suit wins, unless trumped. Winner leads next.',
      'SCORING: If team makes their bid: 10 × bid points. Each overtrick (bag): +1 pt.',
      'Every 10 bags accumulated: −100 pts.',
      'If team fails bid: −10 × bid points.',
      'Nil bid: +100 pts if successful, −100 pts if failed (partner\'s bid still counts).',
      'First team to 500 pts wins. If both reach 500 in same round, higher score wins.',
    ],
  },
  'rummy': {
    quickStart: [
      'Draw a card each turn, then discard one. Aim to form sets (3+ of same rank) and runs (3+ consecutive same suit).',
      'Go out by melding all your cards (with or without one discard).',
      'Score penalty points equal to the face value of unmelded cards in opponents\' hands.',
      'Aces = 1 pt, face cards = 10 pts. Lowest score wins.',
    ],
    full: [
      'Deal 7 cards (2–4 players) or 10 cards (2 players). Remaining cards form the draw pile; flip one card to start discard pile.',
      'On your turn: draw from the deck or discard pile, then discard one card.',
      'MELDS: Sets = 3 or 4 cards of the same rank. Runs = 3+ consecutive cards of the same suit.',
      'You may lay off (add) cards to existing melds on the table.',
      'GO OUT: When you can meld all remaining cards (with one discard), place melds face-up and discard final card.',
      'SCORING: All other players score penalty points for cards in hand.',
      'Number cards = face value, face cards (J/Q/K) = 10 pts, Aces = 1 pt.',
      'Running total. Lowest score when a player reaches an agreed limit (e.g. 100) wins.',
    ],
  },
  'gin-rummy': {
    quickStart: [
      '2 players. Draw a card each turn, discard one. Form sets and runs.',
      'Knock when unmatched cards total 10 or less. Opponent lays off cards on your melds.',
      'Gin (0 unmatched): +25 bonus. Undercut (opponent scores ≤ yours): +25 pts to opponent.',
      'Highest score after agreed rounds wins.',
    ],
    full: [
      'Deal 10 cards each. Flip one card to start discard pile.',
      'Draw from deck or discard pile, then discard one card.',
      'KNOCK: When your unmatched (deadwood) cards total 10 or less, knock by discarding face-down.',
      'Opponent lays off cards onto your melds, then totals their remaining deadwood.',
      'SCORING: Knocker scores (opponent\'s deadwood − knocker\'s deadwood).',
      'GIN: Knock with 0 deadwood → score all of opponent\'s deadwood + 25 bonus.',
      'UNDERCUT: If opponent\'s deadwood ≤ knocker\'s after lay-offs → opponent scores difference + 25.',
      'Play to 100 pts. Winner scores 25 bonus (game bonus) + 25 per hand won (box bonus).',
    ],
  },
  'canasta': {
    quickStart: [
      '2–6 players (best with 4 in 2 teams). Form melds of 3+ cards of the SAME RANK (not sequences).',
      'A canasta = a meld grown to 7 cards of the same rank. Natural (no wilds) = +500 pts, Mixed (with wilds) = +300 pts.',
      'Wild cards (jokers + 2s) can substitute any rank, but wilds must never outnumber natural cards in a meld.',
      'GO OUT: empty your hand AND your team must have laid down at least one canasta. +100 pts bonus.',
      'First team to 5000 pts wins.',
    ],
    full: [
      'Deal 11 cards each. Remaining cards form draw pile; flip one to start discard pile.',
      'MELDS: 3 or more cards of the same rank (NOT sequences). Lay melds face-up on the table.',
      'WILD CARDS: Jokers (50 pts) and 2s (20 pts) may substitute any rank — but wilds must never outnumber natural cards in the same meld.',
      'CANASTA: When a meld reaches 7 cards, it becomes a canasta — fold it into a stack. Natural (no wilds) = 500 pts, Mixed (with wilds) = 300 pts.',
      'GOING OUT: On your turn, meld or lay off ALL remaining cards (with one discard). Your team must have at least one canasta first. Bonus: +100 pts.',
      'ROUND SCORING: sum of card values in melds, minus cards still in hand, plus canasta bonuses.',
      'Card values: Joker = 50, 2 = 20, Ace = 20, 8–K = 10, 4–7 = 5, Black 3 = 5.',
      'INITIAL MELD requirement increases as your score grows (0–1499: 50 pts min, 1500–2999: 90 pts, 3000+: 120 pts).',
      'First team to 5000 pts wins.',
    ],
  },
  'phase-10': {
    quickStart: [
      'Complete 10 specific phases in order. Each phase is a combination of sets and/or runs.',
      'Draw a card, then discard. Complete your current phase by laying down the required cards.',
      'Once your phase is down, play off remaining cards on any laid-down phase.',
      'Penalty points for cards remaining when someone goes out. Fewest points after all 10 phases wins.',
    ],
    full: [
      'Deal 10 cards. Draw from deck or discard pile; discard one card each turn.',
      'PHASES (must be completed in order): 1: 2 sets of 3. 2: 1 set of 3 + 1 run of 4. 3: 1 set of 4 + 1 run of 4. 4: 1 run of 7. 5: 1 run of 8. 6: 1 run of 9. 7: 2 sets of 4. 8: 7 cards of one colour. 9: 1 set of 5 + 1 set of 2. 10: 1 set of 5 + 1 set of 3.',
      'Wild cards (W) can substitute any card. Skip cards (S) force the next player to lose a turn.',
      'LAY DOWN: Once your hand contains the current phase, lay it face-up on your turn.',
      'After laying down, play remaining cards on any table phase (yours or others\').',
      'SCORING: When someone goes out, all others score penalty pts for cards in hand (number cards = face value, wilds/skips = 25 pts).',
      'Players who completed their phase advance to the next. Others repeat same phase.',
      'After all 10 phases (or agreed rounds), lowest score wins.',
    ],
  },
  'uno': {
    quickStart: [
      'Match the top card of the discard pile by colour, number, or symbol.',
      'Draw 2 if you can\'t play. Shout "UNO!" when you have 1 card left.',
      'Special cards: Skip, Reverse, Draw 2, Wild, Wild Draw 4.',
      'When a player goes out, others score penalty pts equal to cards in hand. First to 500 ends the game — lowest score wins.',
    ],
    full: [
      'Deal 7 cards each. Flip top card to start discard pile.',
      'On your turn: play a matching card (same colour, number, or symbol). If unable, draw one — then play it if possible, otherwise keep it.',
      'ACTION CARDS: Skip (next player loses turn), Reverse (direction changes), Draw 2 (next player draws 2 and loses turn).',
      'WILD cards: change colour to any colour. Wild Draw 4: change colour AND next player draws 4 (only play if you have no matching colour).',
      'UNO: call "UNO!" when playing your second-to-last card. If caught not calling, draw 2.',
      'SCORING: When a player goes out, count cards in all other hands.',
      'Number cards = face value, action cards = 20 pts each, Wild/Wild Draw 4 = 50 pts each.',
      'Cumulative total. First player to reach 500 pts ends the game. Lowest score wins.',
    ],
  },
  'cabo': {
    quickStart: [
      'Each player has 4 face-down cards. You may peek at your bottom 2 cards at the start.',
      'Draw a card and either swap it with one of yours (discarding the old) or discard it (using any special ability).',
      'Call "Cabo" when you think your hand total is lowest. Everyone gets one more turn.',
      'Lowest total wins the round. First to 100 pts loses; lowest score wins.',
    ],
    full: [
      'Deal 4 cards face-down to each player. Peek at your own bottom 2 cards.',
      'On your turn: flip top of draw pile. Either swap it with any of your cards (discard old card) or discard it.',
      'SPECIAL ABILITIES (when discarding): 7/8 = peek at one of your own cards. 9/10 = peek at an opponent\'s card. J/Q = swap one of your cards with an opponent\'s (blind). K (black) = swap freely (you may look at your card). K (red) = no ability.',
      'CABO: Any player may call "Cabo" instead of drawing. All other players get one more turn.',
      'REVEAL: All cards are flipped. Lowest total wins the round.',
      'SCORING: Losing players score the value of their hand. Cabo caller: if lowest or tied, scores 0; if not lowest, +5 penalty.',
      'Aces = 1, number cards = face value, J/Q = 11/12, K = 13, Joker = −1.',
      'Cumulative. First to 100 pts is out. Last player standing (or lowest at agreed end) wins.',
    ],
  },
  'cribbage': {
    quickStart: [
      '2–4 players. Deal 6 cards; each player discards 2 to the "crib" (belongs to the dealer).',
      'The starter card is cut; if it\'s a Jack, dealer pegs 2 ("his heels").',
      'Play cards alternately, scoring for 15s, pairs, runs, and 31s. Then count your hand.',
      'First to 121 points wins.',
    ],
    full: [
      'Deal 6 cards (5 in 3–4 player game). Each player discards 2 to the crib. Cut a starter card.',
      'PEGGING (play phase): alternate playing cards, calling cumulative total. Score: reaching 15 = 2 pts, reaching 31 = 2 pts (or 1 pt for "go" if opponent can\'t play). Pairs = 2 pts, 3-of-a-kind = 6, four-of-a-kind = 12. Run of 3+ = pts equal to run length.',
      'COUNTING (show phase): count your hand + starter card, then dealer counts crib.',
      'Count scores: 15s = 2 pts each, pairs = 2 pts, runs = length of run, flush (4+ same suit) = 4–5 pts, nobs (Jack of starter suit in hand) = 1 pt.',
      'First player to peg to 121 wins immediately (even mid-hand).',
    ],
  },
  'doppelkopf': {
    quickStart: [
      '4 players, 2 teams (Re vs Kontra). Teams are secret — revealed by who holds the Queens of Clubs.',
      'Aim to win tricks worth 120+ points (Re) or to stop them (Kontra).',
      'Winning team scores 1 game point per player; bonuses for extra achievements.',
    ],
    full: [
      '48-card deck (no 2s–8s). Deal 12 cards each.',
      'TEAMS: The two players holding Queens of Clubs are "Re" team; others are "Kontra". (In solo games, one player plays alone.)',
      'TRUMP ORDER (highest to lowest): Q♣ Q♠ Q♥ Q♦ J♣ J♠ J♥ J♦ A♦ 10♦ K♦ 9♦ 8♦.',
      'Then plain suits (A 10 K 9 8) — no 7s.',
      'TRICK PLAY: Lead any card. Others must follow suit; if unable, play any card. Highest trump wins; if no trump, highest of led suit.',
      'SCORING: Count card points in won tricks. A=11, 10=10, K=4, Q=3, J=2, 9/8/7=0. Total = 240.',
      'Re wins if their total ≥ 121. Both teams score game points based on margin and bonuses (e.g. winning without opponents scoring = extra point).',
    ],
  },
  'skat': {
    quickStart: [
      '3 players. Deal 10 cards each with 2 cards face-down (the skat).',
      'Players bid to become the "declarer" who picks up the skat and names the trump suit.',
      'Declarer aims to win card points; defenders aim to stop them.',
    ],
    full: [
      '32-card deck (7–A in each suit). Deal 10 cards each; 2 cards face-down form the skat.',
      'BIDDING: Players bid game values (18, 20, 22...). Highest bidder becomes declarer.',
      'SKAT: Declarer picks up skat, discards 2 cards face-down, then declares: suit game, grand (only jacks trump), or null (avoid all tricks).',
      'JACKS: In suit/grand games, all four jacks are the highest trumps (♣ J highest).',
      'TRICK PLAY: 10 tricks. Follow suit; if unable, play any card. Jacks beat all suit cards.',
      'CARD VALUES: A=11, 10=10, K=4, Q=3, J=2. Others = 0. Total = 120.',
      'SCORING: Declarer must reach 61 pts (or 31 in null). Game value = base value × multipliers.',
      'Win: add game value to score. Lose: subtract double game value.',
    ],
  },
  'catan': {
    quickStart: [
      'Collect resources (Wood, Brick, Wheat, Sheep, Ore) to build roads, settlements, cities, and development cards.',
      'Settlements = 1 VP, Cities = 2 VP. Longest Road and Largest Army = 2 VP each.',
      'First player to 10 Victory Points wins.',
    ],
    full: [
      'Set up the island from hex tiles; place initial settlements and roads.',
      'Each turn: roll 2 dice. All players collect resources from hexes numbered with the roll adjacent to their settlements/cities.',
      '7 = robber moves: no resources produced for that number; robber player steals 1 card from a player adjacent to new robber location.',
      'BUILD: Road = Wood + Brick. Settlement = Wood + Brick + Wheat + Sheep. City (upgrade) = 3 Ore + 2 Wheat. Dev card = Ore + Wheat + Sheep.',
      'TRADE: 4:1 with bank, 3:1 at generic harbours, 2:1 at specific harbours, or trade with other players.',
      'DEV CARDS: Knight (move robber + steal), Victory Point, Road Building, Year of Plenty, Monopoly.',
      'SPECIAL: Longest Road (5+ consecutive roads) = 2 VP. Largest Army (3+ knights) = 2 VP.',
      'WIN: Reach 10 Victory Points on your turn.',
    ],
  },
  'ticket-to-ride': {
    quickStart: [
      'Claim railway routes by playing matching coloured train cards.',
      'Score points for routes claimed. Complete destination tickets (bonus) or fail them (penalty).',
      'When one player has 2 or fewer train pieces left, all players get one more turn, then score.',
    ],
    full: [
      'Each player starts with 45 trains, 4 train cards, and 3 destination tickets (keep at least 2).',
      'On your turn: draw 2 train cards (from deck or face-up), claim a route (play matching cards), or draw destination tickets.',
      'CLAIMING: Play the exact number of cards matching the route colour. Grey routes accept any single colour.',
      'ROUTE POINTS: 1 train = 1, 2 = 2, 3 = 4, 4 = 7, 5 = 10, 6 = 15.',
      'DESTINATION TICKETS: Connect two cities shown → add bonus points. Fail → subtract points.',
      'END GAME: When a player has ≤2 trains, all players (including them) get one final turn.',
      'BONUS: Longest continuous route = 10 pts.',
      'Highest score wins.',
    ],
  },
  'carcassonne': {
    quickStart: [
      'Take turns placing tiles to build a medieval landscape of cities, roads, and monasteries.',
      'Place a meeple (follower) on the tile to claim a feature. Score when features complete.',
      'At game end, score incomplete features and fields.',
    ],
    full: [
      'Each player has 7 meeples. On your turn: draw a tile, place it (must match edges), optionally place a meeple.',
      'FEATURES: City (surrounded by walls), Road (ends at city/crossroads/dead-end), Monastery (surrounded by 8 tiles), Field (grass area).',
      'MEEPLE PLACEMENT: Place on any unclaimed feature of the tile just placed.',
      'SCORING (completed features during game): City = 2 pts/tile + 2 pts/shield. Road = 1 pt/tile. Monastery = 9 pts (tile + all 8 surrounding).',
      'Multiple players on same feature (via expansion): all score.',
      'END GAME scoring: Incomplete city = 1 pt/tile + 1 pt/shield. Incomplete road = 1 pt/tile. Incomplete monastery = 1 + adjacent tiles. Fields: 3 pts per completed adjacent city.',
      'Highest score wins.',
    ],
  },
  'scrabble': {
    quickStart: [
      'Take turns placing letter tiles on the board to form words. Words must connect to existing tiles.',
      'Score = sum of letter values. Double/Triple Letter and Double/Triple Word squares multiply scores.',
      'Bingo (using all 7 tiles): +50 pts. Game ends when all tiles are used.',
      'Subtract unplayed tile values at end. Highest score wins.',
    ],
    full: [
      'Each player draws 7 tiles. The first word must cross the centre square.',
      'Each word must read left-to-right or top-to-bottom and connect to existing tiles.',
      'All new words formed (including cross-words) score on the same turn.',
      'TILE VALUES: Blank = 0, A/E/I/O/U/L/N/S/T/R = 1, D/G = 2, B/C/M/P = 3, F/H/V/W/Y = 4, K = 5, J/X = 8, Q/Z = 10.',
      'PREMIUM SQUARES: DL = double letter, TL = triple letter, DW = double word, TW = triple word.',
      'Premium squares only apply the first time a tile covers them.',
      'BINGO: Using all 7 tiles in one move = +50 bonus points.',
      'ENDING: When the bag is empty and one player uses all tiles, or all players pass twice.',
      'All players subtract face values of unplayed tiles. The player who finished adds others\' subtracted tiles to their score.',
      'Highest final score wins.',
    ],
  },
  'backgammon': {
    quickStart: [
      'Move all 15 pieces around the board into your home board, then bear them off.',
      'Roll 2 dice each turn; move pieces the shown numbers (can split between two pieces or use both on one).',
      'Hit a blot (single opponent piece) to send it to the bar; it must re-enter before other moves.',
      'First to bear off all pieces wins.',
    ],
    full: [
      'Each player has 15 checkers. Starting position is fixed. White moves clockwise, Black counter-clockwise.',
      'MOVING: Roll 2 dice; move checkers the exact number shown. Doubles = play each die twice (4 moves total).',
      'BLOCKED POINTS: You cannot land on a point holding 2+ opponent checkers.',
      'HITTING: Land on a point with exactly 1 opponent checker (blot) → send it to the bar.',
      'BAR: A player with checkers on the bar must enter them in the opponent\'s home board first.',
      'BEARING OFF: When all your checkers are in your home board (points 1–6), start bearing off. Roll a number → remove a checker from that point (or from a higher point if that point is empty).',
      'DOUBLING CUBE: Optional. At the start of your turn, offer to double the stakes. Opponent may accept or resign.',
      'GAMMON: Win before opponent bears off any → double the stake. Backgammon: win while opponent has a checker on bar or in your home board → triple the stake.',
    ],
  },
  'sequence': {
    quickStart: [
      '2–12 players (in 2 or 3 teams). Play a card from your hand and place a chip on the matching board space.',
      'Form a sequence of 5 chips in a row (horizontally, vertically, or diagonally).',
      'Jacks: one-eyed = remove an opponent chip; two-eyed = wild (play anywhere).',
      'First team to required sequences wins (1 team: 2 seq., 2 teams: 2 seq., 3 teams: 1 seq.).',
    ],
    full: [
      'The board shows all 52 cards twice (minus Jacks). Corner spaces are free (wildcards for all players).',
      'On your turn: play a card, place your chip on a matching space, discard, draw a new card.',
      'JACKS: One-eyed jacks (♠J, ♥J) = remove any opponent\'s chip. Two-eyed jacks (♦J, ♣J) = place on any empty space.',
      'DEAD CARD: If all matching spaces are blocked, discard and draw without placing.',
      'SEQUENCES: 5 in a row of your colour. Corner free spaces count for any player.',
      'WIN: Depending on player count — 2 teams need 2 sequences each; 3 teams need 1 sequence each.',
      'Track sequences made. Highest when game ends (or first to goal) wins.',
    ],
  },
  'petanque': {
    quickStart: [
      'Teams throw metal balls (boules) as close as possible to the small target ball (cochonnet/jack).',
      'Closest team scores 1 point per ball closer than the nearest opponent ball.',
      'First team to 13 points wins.',
    ],
    full: [
      'Teams: 1v1 (3 boules each), 2v2 (3 each), or 3v3 (2 each). Toss the cochonnet (jack) 6–10 metres.',
      'Teams alternate throwing. The team NOT holding (closest to jack) throws until they hold or run out.',
      'POINTING: Throw to get close. SHOOTING: Throw to knock opponent boules away.',
      'END OF ROUND (mène): When all boules are thrown, the team with the closest boule scores.',
      'Score = number of your boules closer to jack than the nearest opponent boule.',
      'First to 13 points wins the game.',
      'If no team reaches 13 after agreed rounds, highest score wins.',
    ],
  },
  'croquet': {
    quickStart: [
      'Hit balls through hoops in the correct order using a mallet.',
      'Score 1 point per hoop cleared. Running a hoop earns a bonus stroke.',
      'Hitting another ball (roquet) earns 2 bonus strokes.',
      'First to complete all hoops and hit the peg wins.',
    ],
    full: [
      'Standard Association Croquet: each side has 2 balls. Complete 12 hoops (6 each direction) + peg in order.',
      'STROKES: Each turn starts with 1 stroke. Running a hoop = 1 bonus stroke. Roqueting (hitting another ball) = 2 bonus strokes.',
      'CROQUET SHOT: After roqueting, place your ball touching theirs. Strike your ball to move both.',
      'CONTINUATION: After a croquet shot you get 1 continuation stroke.',
      'Each ball may be roqueted once per turn (reset after running a hoop).',
      'WINNING: First side to run all hoops and hit the peg with both balls wins.',
      'GARDEN CROQUET: simplified rules — score 1 per hoop run, first to agreed total wins.',
    ],
  },
  'bowling': {
    quickStart: [
      '10 frames. Each frame: roll up to 2 balls to knock down all 10 pins.',
      'Strike (all 10 on first roll): score 10 + next 2 balls\' total.',
      'Spare (all 10 on second roll): score 10 + next ball\'s total.',
      'Open frame: score = pins knocked down.',
      '10th frame: if you get a strike or spare, you get bonus rolls. Maximum score is 300.',
    ],
    full: [
      '10 frames per game. In each frame, roll up to 2 balls.',
      'STRIKE (X): All 10 pins on the first ball. Score = 10 + sum of next 2 deliveries.',
      'SPARE (/): All remaining pins on the second ball. Score = 10 + next 1 delivery.',
      'OPEN FRAME: Neither strike nor spare. Score = pins knocked down.',
      '10TH FRAME: If you roll a strike, you get 2 more rolls. If you roll a spare, you get 1 more roll. Otherwise just 2 rolls.',
      'PERFECT GAME: 12 consecutive strikes = 300 points.',
      'Highest score wins.',
    ],
  },
  'farkle': {
    quickStart: [
      'Roll 6 dice. You must score at least one die or it\'s a Farkle (lose all unbanked points this turn).',

      'Scoring: 1s = 100 pts, 5s = 50 pts, three 1s = 1000, three of any kind = that number × 100 (e.g., three 4s = 400).',
      'After scoring, choose to bank your points or roll remaining dice to add more.',
      'If all 6 dice score, you can roll all 6 again (hot dice).',
      'Must reach 1000 pts in a single turn to open your account. After that, bank at any time.',
      'First to 10 000 wins (everyone else gets one last turn to beat them).',
    ],
    full: [
      'On your turn, roll all 6 dice.',
      'SCORING COMBINATIONS:',
      '  Single 1 = 100 points',
      '  Single 5 = 50 points',
      '  Three 1s = 1000 points',
      '  Three 2s = 200 points',
      '  Three 3s = 300 points',
      '  Three 4s = 400 points',
      '  Three 5s = 500 points',
      '  Three 6s = 600 points',
      '  Four of a kind = double the three-of-a-kind score',
      '  Five of a kind = triple the three-of-a-kind score',
      '  Six of a kind = 3000 points',
      '  Straight 1-2-3-4-5-6 = 1500 points',
      '  Three pairs = 1500 points',
      'FARKLE: If no dice score on a roll, it\'s a Farkle — you lose all unbanked points for that turn.',
      'HOT DICE: If all 6 dice score in a single roll, you may roll all 6 again and add to your total.',
      'BANKING: After scoring dice, you may bank your points (add to total) or continue rolling remaining dice.',
      'OPENING: You must score at least 1000 points in a single turn before you can bank.',
      'WINNING: First to reach 10 000 triggers final round — all other players get one more turn.',
      'Player with highest score (at least 10 000) after final round wins.',
    ],
  },
  'table-tennis': {
    quickStart: [
      'Each game is played to 11 points (win by 2). Serve alternates every 2 points.',
      'A match is best of 3 or best of 5 games.',
      'Serve must bounce once on your side, then once on the opponent\'s side.',
      'Most games won wins the match.',
    ],
    full: [
      'GAME: First to 11 points, win by 2. At 10-10 (deuce), serve alternates every 1 point until someone leads by 2.',
      'SERVE: Ball is tossed 16cm+, hit so it bounces on server\'s side, then clears the net and bounces on receiver\'s side.',
      'DOUBLES: Serve must go from server\'s right half-court to receiver\'s right half-court diagonally.',
      'SCORING: A point is won when the opponent fails to return the ball correctly.',
      'MATCH: Best of 3 (first to 2 wins) or best of 5 (first to 3 wins). Sides are switched after each game.',
      'At game 5 (or 3 in best of 3), players switch ends at 5 points.',
    ],
  },
  'billiards': {
    quickStart: [
      'Most common format: 8-ball pool. Pot all your balls (stripes or solids) then the 8-ball to win.',
      'Break: one player breaks the rack. The first ball potted determines which group each player plays.',
      'Potting the 8-ball before your group is cleared = instant loss.',
      'Track frames won across the match.',
    ],
    full: [
      '8-BALL: Each player takes one group (solids 1–7 or stripes 9–15). Pot all your balls, then pot the 8.',
      'BREAK: Rack all 15 balls. The breaker must hit the rack and either pot a ball or drive 4 balls to cushions.',
      'OPEN TABLE: After break, table is "open" until first ball is potted (determines groups).',
      'FOULS: Potting the cue ball (scratch), failing to hit your own ball first, no ball reaches a cushion after contact. Opponent gets ball-in-hand.',
      'WINNING: Pot the 8-ball when all your group is cleared. Must call pocket for the 8.',
      'LOSING: Pot the 8-ball on the break (re-rack or win depending on house rules), pocket 8 before group is cleared, or scratch on the 8.',
      '9-BALL (alternative): Balls 1–9 on table. Must hit lowest ball first. Pot the 9-ball to win (legally).',
      'Track frames (individual games) won. Highest frame count wins the session.',
    ],
  },
  'badminton': {
    quickStart: [
      'Rally scoring — both players can score on any rally.',
      'Games to 21 points, win by 2. At 29-29, first to 30 wins.',
      'Match is best of 3 games.',
      'Serve must be hit below the waist and land in the correct service box.',
    ],
    full: [
      'SCORING: Rally scoring — point is awarded after every rally, regardless of who served.',
      'GAME: First to 21 points, win by 2. If tied at 29-29, first to 30 points wins.',
      'MATCH: Best of 3 games. Players change ends after each game, and in game 3 when first player reaches 11.',
      'SERVICE: Server and receiver stand in diagonally opposite service courts. Serve must be hit below the waist (below server\'s last rib). Shuttle must land in correct service box.',
      'IN PLAY: Shuttle must pass over the net and land inside the court boundaries.',
      'FAULTS: Shuttle lands out, hits net, player touches net, shuttle caught/carried. Point to opponent.',
      'DOUBLES: Players cover specific halves of court during serve; otherwise whole court is in play.',
    ],
  },
  'foosball': {
    quickStart: [
      'Score by shooting the ball into the opponent\'s goal using the rods.',
      'Most goals wins. Common formats: first to 5, first to 10, or timed.',
      'Spinning (360° rotation of a rod) is usually not allowed.',
      'Track goals per game and games won across the match.',
    ],
    full: [
      'SERVE: Ball is served through the side hole to the middle rod. Play begins immediately.',
      'SCORING: A goal counts if the ball fully crosses the goal line. Kicked-back goals count.',
      'SPINNING: Players may not rotate a rod a full 360° before or after striking the ball (house rules vary).',
      'DEAD BALL: If the ball stops where no rod can reach it, re-serve.',
      'GAME: Common formats — first to 5 goals, first to 10, or a set time limit.',
      'MATCH: Best of 3 or 5 games. Switch sides between games.',
      'RESET: If the ball exits the table, re-serve to the team that did not last touch it.',
      'Track goals per game and games won to determine the match winner.',
    ],
  },
  'kubb': {
    quickStart: [
      '2 teams, 5 kubbs per side. Place kubbs in a line on each baseline.',
      'Team 1 throws 6 batons to knock over Team 2\'s field kubbs. Knocked kubbs are thrown to Team 1\'s half.',
      'Team 2 must knock over any thrown kubbs first (field kubbs), then baseline kubbs.',
      'After knocking all kubbs, throw at the King in the middle. First team to topple the King wins!',
      'If you knock the King before all kubbs: your team loses.',
    ],
    full: [
      'Setup: 5 kubbs on each baseline, King in the middle. Court is 5×8 m (can be smaller for casual play).',
      'TURN: Each team throws 6 batons (underarm, end-over-end or spin) trying to knock over opponent\'s kubbs.',
      'FIELD KUBBS: Knocked baseline kubbs are tossed by the opponent into their own half of the pitch.',
      'PRIORITY: If field kubbs remain standing, the attacking team must knock them over first before targeting baseline kubbs.',
      'Field kubbs that land outside the court are placed 1 metre from the King.',
      'ADVANTAGE LINE: If field kubbs exist, the attacking team may advance to the field kubb nearest the King.',
      'WIN CONDITION: Knock over all opponent kubbs (field + baseline), then topple the King.',
      'PENALTY: Knocking the King before all opponent kubbs are down = instant loss.',
      'Teams alternate turns. Highest number of wins across agreed matches wins the session.',
    ],
  },
  'molkky': {
    quickStart: [
      'Set up 12 numbered pins (1–12) in a triangular formation 3–4 m from the throwing line.',
      'Throw the Mölkky skittle underarm to knock over pins.',
      'Score: 1 pin knocked = its face value. 2+ pins knocked = number of pins knocked.',
      'First to reach EXACTLY 50 wins. If you exceed 50, your score drops back to 25.',
      'Miss 3 times in a row: eliminated.',
    ],
    full: [
      'Setup: 12 pins numbered 1–12 in a triangular formation, 3–4 metres from the throwing line.',
      'On your turn, throw the Mölkky skittle underarm from behind the throwing line.',
      'SCORING: If exactly 1 pin falls = score that pin\'s number. If 2 or more pins fall = score the count of fallen pins.',
      'Pins are reset upright where they fell after each throw (they spread out over time).',
      'TARGET: Reach exactly 50 points.',
      'OVERSHOOT: Score exceeds 50 → score drops back to 25.',
      'THREE MISSES: Knock over no pins 3 turns in a row → that player is eliminated.',
      'Winner is the first to reach exactly 50 points.',
    ],
  },
  'disc-golf': {
    quickStart: [
      'Play each hole by throwing your disc from the tee toward the basket goal.',
      'From where your disc lands, throw again. Repeat until the disc lands in the basket.',
      'Count every throw as 1 stroke. Par is usually 3 per hole.',
      'Lowest total strokes across all holes wins.',
    ],
    full: [
      'Each hole starts at a designated tee pad. Throw toward the target basket.',
      'After each throw, the next throw is made from where the disc came to rest (lie).',
      'Hole is completed when the disc lands in and stays in the metal basket.',
      'SCORING: Count every throw. Below par = birdie (−1), eagle (−2), etc. Above par = bogey (+1), double bogey (+2).',
      'Out of bounds (OB): add 1 stroke penalty, throw from where disc went OB (or designated drop zone).',
      'Mandatory routes (mandos): disc must pass a specific side of a marker — if not, +1 stroke and re-throw.',
      'HANDICAP: Optional. Players subtract their handicap from total score to level the field.',
      'Lowest total strokes after all holes wins.',
    ],
  },
  'cornhole': {
    quickStart: [
      '2 teams of 1–2 players. Boards are 9 metres apart. Each team has 4 bags of one colour.',
      'Teams alternate throwing all 4 bags per round. Hole = 3 pts, on board = 1 pt.',
      'CANCELLATION SCORING: subtract the lower team\'s score from the higher team\'s score each round.',
      'First team to reach exactly 21 wins. You can go over 21 — the game continues.',
    ],
    full: [
      'Setup: two boards 9 m apart (8.5 m hole-to-hole for official play). Each player/team gets 4 bags.',
      'THROWING: Teams alternate one bag at a time from the same side. All 4 bags per team per round.',
      'SCORING: Bag through the hole = 3 pts. Bag on the board surface = 1 pt. Bag bounced onto board = 0 pts (remove it).',
      'CANCELLATION: At end of each round, subtract lower team\'s points from higher team\'s points. Only the difference is added.',
      'Example: Team A scores 7, Team B scores 4 → Team A earns 3 pts that round.',
      'WINNING: First team to reach exactly 21 points wins.',
      'BUST: Some house rules: going over 21 resets you to 11 (or 15) — agree before playing.',
      'SKUNK: If a team reaches 11 and the opponent has 0, the game may be called (optional rule).',
    ],
  },
}

const QUICK_START_NO: Record<string, string[]> = {
  'maxi-yatzy': [
    'Kast 6 terninger opp til 3 ganger per tur — hold terninger mellom kastene.',
    'Skriv inn én kategori per tur. Hver kategori kan bare brukes én gang.',
    'Øvre seksjon (Ettere–Seksere): summer matchende terninger. Bonus 100 p ved sum ≥ 84.',
    'Nedre seksjon: 1 Par, 2 Par, 3 Par, 3/4/5 Like, Rekker, Hytte (2+3), Hus (3+3), Tårn (2+4), Sjanse, Maxi Yatzy (100 p).',
    'Høyeste totalscore vinner.',
  ],
  'yatzy': [
    'Kast 5 terninger opp til 3 ganger per tur — hold terninger mellom kastene.',
    'Skriv inn én kategori per tur. Hver kan bare brukes én gang.',
    'Øvre seksjon (Ettere–Seksere): sum av matchende terninger. Bonus 50 p ved sum ≥ 63.',
    'Nedre seksjon: 1 Par, 2 Par, 3/4 Like, Fullt Hus, Liten/Stor Straight, Sjanse, Yatzy (50 p).',
    'Høyeste totalscore vinner.',
  ],
  'darts-501': [
    'Hver spiller starter med 501 poeng.',
    'Kast 3 piler i tur. Trekk poengsummen fra totalen din.',
    'Du må avslutte på nøyaktig 0 — siste pil må treffe en dobling (eller blink).',
    'Bust (under 0 eller nøyaktig 1): poengsummen tilbakestilles til start av turen.',
    'Første til nøyaktig 0 vinner.',
  ],
  'darts-301': [
    'Hver spiller starter med 301 poeng.',
    'Kast 3 piler i tur. Trekk poengsummen fra totalen din.',
    'Du må avslutte på nøyaktig 0 — siste pil må treffe en dobling (eller blink).',
    'Bust (under 0 eller nøyaktig 1): poengsummen tilbakestilles.',
    'Første til nøyaktig 0 vinner.',
  ],
  'darts-cricket': [
    'Tall i spill: 15, 16, 17, 18, 19, 20 og Blink.',
    'Treff et tall 3 ganger for å "lukke" det. Merker: 1 = /, 2 = X, 3 = lukket (⊗).',
    'Etter lukking scorer ekstra treff poeng — men bare hvis motstanderen ikke har lukket tallet ennå.',
    'Vinn ved å lukke alle tall OG ha høyest (eller lik) score.',
  ],
  'hearts': [
    '3–6 spillere, standard 52-korts kortstokk.',
    'Hvert stikk: høyeste kort av ledet farge vinner. Hjerter er ikke trumf.',
    'Poeng: Hjerter = 10 p hvert (Hjerteess = 20 p), Spardam = 100 p, Ruterknekt = −100 p.',
    'Skyt månen (valgfritt): ta ALLE hjerter + Spardam → du scorer 0, alle andre får 240 p.',
    'Spillet slutter når noen når 500 poeng. Lavest score vinner.',
  ],
  'farkle': [
    'Kast 6 terninger. Du MÅ score minst én terning, ellers er det Farkle (tap alle ubankede poeng).',
    'Poeng: 1 = 100 p, 5 = 50 p, tre ettere = 1000, tre like = antall × 100 (f.eks. tre femmere = 500).',
    'Etter scoring: bank poengene eller kast gjenstående terninger for å samle mer.',
    'Alle 6 terninger scorer: hot dice — kast alle 6 igjen og legg til.',
    'Trenger 1000 p i én tur for å åpne kontoen. Første til 10 000 vinner (alle andre får én siste tur).',
  ],
  'spades': [
    '4 spillere, 2 lag. Spar er alltid trumf.',
    'Alle byr på antall stikk de forventer. Laget scorer 10 p per budt stikk ved å nå budet.',
    'Overtrekk (poser) gir 1 p, men 10 poser = −100 p. Underbuding koster 10 p per stikk under.',
    'Første lag til 500 p vinner.',
  ],
  'rummy': [
    'Trekk et kort, kast ett. Mål: form grupper (3+ like rang) og rekker (3+ påfølgende, samme farge).',
    'Gå ut ved å legge ned alle kortene dine.',
    'Straffepoeng lik kortverdi av ulagte kort i motstandernes hender.',
    'Bildekort = 10 p, ess = 1 p. Lavest score vinner.',
  ],
  'gin-rummy': [
    '2 spillere. Trekk og kast ett kort per tur. Form grupper og rekker.',
    'Bank når gjenstående ubrukte kort summerer til 10 eller mindre.',
    'Motstanderen legger av på dine kombinasjoner, teller gjenstående.',
    'Gin (0 ubrukte): +25 bonuspoeng. Underkutt (motstanderens gjenstående ≤ din): +25 p til motstanderen.',
    'Høyest score etter avtalte runder vinner.',
  ],
  'canasta': [
    '2–6 spillere (best med 4 i 2 lag). Form kombinasjoner av 3+ kort med SAMME RANG (ikke rekker).',
    'En canasta = en kombinasjon som vokser til 7 kort av samme rang. Naturlig (uten jokere) = +500 p, Blandet (med jokere) = +300 p.',
    'Jokere og 2-ere kan erstatte hvilken som helst rang, men må aldri være i flertall mot naturlige kort.',
    'GÅ UT: tøm hånden OG laget må ha lagt ned minst én canasta. +100 p bonus.',
    'Første lag til 5000 p vinner.',
  ],
  'phase-10': [
    'Fullfør 10 spesifikke faser i rekkefølge. Trekk et kort, kast ett.',
    'Faser: grupper (like rang) og rekker (påfølgende). Eks. fase 1: 2 grupper à 3 kort.',
    'Jokere kan erstatte alle kort. Skip-kort gjør at neste spiller mister en tur.',
    'Straffepoeng for gjenværende kort etter at noen går ut. Lavest score vinner.',
  ],
  'uno': [
    'Match topkortet etter farge, tall eller symbol.',
    'Trekk 2 hvis du ikke kan spille. Ropa "UNO!" med 1 kort igjen.',
    'Spesialkort: Hopp, Snu, Trekk 2, Wild, Wild Trekk 4.',
    'Når noen går ut, scorer andre straffepoeng. Første til 500 avslutter spillet — lavest score vinner.',
  ],
  'cabo': [
    '4 kort ned. Kikk på dine to nederste i starten.',
    'Trekk et kort og bytt det mot et av dine (kast gammel), eller kast det (bruk spesialeffekt).',
    'Ropa "Cabo" når du tror håndsummen er lavest. Alle andre får én tur til.',
    'Lavest håndsum vinner runden. Første til 100 p er ute — lavest score til slutt vinner.',
  ],
  'cribbage': [
    '2–4 spillere. Del 6 kort; alle kaster 2 til "kribben" (tilhører utdeleren).',
    'Vend et startkort. Er det en knekt, scorer utdeleren 2 poeng.',
    'Spill kort om hverandre og score for 15-ere, par, rekker og 31-ere. Deretter telles håndene.',
    'Første til 121 poeng vinner.',
  ],
  'doppelkopf': [
    '4 spillere, 2 lag (Re mot Kontra). Lag holdes hemmelig — avsløres av hvem som holder kloverkonginnene.',
    'Mål: ta stikk verdt 120+ poeng (Re) eller stoppe dem (Kontra).',
    'Vinnerlaget scorer 1 spillpoeng per spiller; bonuser for ekstra prestasjoner.',
  ],
  'skat': [
    '3 spillere. Del 10 kort med 2 skjulte (skaten).',
    'Spillerne byr for å bli deklaranten — tar opp skaten og velger trumf.',
    'Deklaranten forsøker å vinne kortpoeng; forsvarerne forsøker å stoppe dem.',
  ],
  'catan': [
    'Samle ressurser (Tre, Leire, Korn, Sau, Malm) for å bygge veier, bosetninger, byer og kort.',
    'Bosetninger = 1 sp, Byer = 2 sp. Lengste vei og Største hær = 2 sp hver.',
    'Første til 10 seierpoeng vinner.',
  ],
  'ticket-to-ride': [
    'Krev jernbaneruter ved å spille matchende fargede togsett.',
    'Score poeng for krevde ruter. Fullfør destinasjonskort (bonus) eller mislykkes (minus).',
    'Når en spiller har ≤2 togsett igjen, alle får én tur til — deretter telles score.',
  ],
  'carcassonne': [
    'Legg fliser etter tur for å bygge et middelaldersk landskap av byer, veier og klostre.',
    'Plasser en brikke på flisen for å kreve en funksjon. Score når funksjoner fullføres.',
    'Ved slutten: score ufullstendige funksjoner og jordbruksområder.',
  ],
  'scrabble': [
    'Legg bokstavbrikker for å forme ord. Ord må kobles til eksisterende brikker.',
    'Score = sum av bokstavverdier. Dobbelt/trippelt-felt multipliserer score.',
    'Bingo (alle 7 brikker i ett trekk): +50 p. Trekk fra ubrukte brikker til slutt.',
    'Høyest score vinner.',
  ],
  'backgammon': [
    'Flytt alle 15 brikker rundt brettet inn i hjemme-bordet ditt, deretter bær dem av.',
    'Kast 2 terninger per tur; flytt brikker de viste tallene.',
    'Treff en enkelt motstanderbrikke: send den til bar — den må inn igjen før andre trekk.',
    'Første til å bære av alle brikker vinner.',
  ],
  'sequence': [
    '2–12 spillere i lag. Spill et kort og plasser en brikke på matchende brett-felt.',
    'Form en sekvens på 5 brikker på rad (horisontalt, vertikalt eller diagonalt).',
    'Knekter: én øye = fjern motstanderbrikke; to øyne = joker (spill hvor som helst).',
    'Første lag til nødvendig antall sekvenser vinner.',
  ],
  'petanque': [
    'Lag kaster kuler (boules) så nær målkulen (cochonnet) som mulig.',
    'Nærmeste lag scorer 1 poeng per kule nærmere enn motstanderens nærmeste kule.',
    'Første lag til 13 poeng vinner.',
  ],
  'bowling': [
    '10 frames. Hvert frame: kast opp til 2 ganger for å velte alle 10 kjegler.',
    'Strike (alle 10 på første kast): score 10 + neste 2 kast.',
    'Spare (alle 10 på andre kast): score 10 + neste kast.',
    'Åpent frame: score = veltede kjegler. Maks totalscore er 300.',
  ],
  'croquet': [
    'Slå baller gjennom ringer i riktig rekkefølge med en kølle.',
    'Score 1 poeng per ring passert. Å passere en ring gir et bonusslag.',
    'Treffe en annens ball (roquet) gir 2 bonusslag.',
    'Første til å fullføre alle ringer og treffe pelen vinner.',
  ],
  'table-tennis': [
    'Hvert sett spilles til 11 poeng (vinn med 2). Serve byttes hver 2. poeng.',
    'Kamp er best av 3 eller best av 5 sett.',
    'Serve må sprette én gang på din side, deretter over nettet og én gang på motstanderens side.',
    'Flest sett vunnet vinner kampen.',
  ],
  'billiards': [
    'Vanligste format: 8-ball pool. Sett inn alle dine baller (striper eller solide), deretter 8-ballen.',
    'Break: én spiller bryter. Første ball inn avgjør hvilken gruppe hver spiller spiller.',
    'Sette inn 8-ballen før din gruppe er tømt = øyeblikkelig tap.',
    'Spor frames vunnet gjennom kampen.',
  ],
  'badminton': [
    'Rally-scoring — begge kan score uansett hvem som servet.',
    'Sett til 21 poeng, vinn med 2. Ved 29-29 vinner første til 30.',
    'Kamp er best av 3 sett.',
    'Serve må slås under livet og lande i riktig servefelt.',
  ],
  'foosball': [
    'Score mål ved å skyte ballen i motstanderens mål med stengene.',
    'Flest mål vinner. Vanlige formater: først til 5, 10, eller på tid.',
    'Spinning (360° rotasjon av en stang) er vanligvis ikke tillatt.',
    'Spor mål per kamp og kamper vunnet.',
  ],
  'kubb': [
    '2 lag, 5 kubber per side. Plasser kubber på baselinje, Kongen i midten.',
    'Kast 6 kastepinner for å velte motstanderens kubber. Veltede kubber kastes inn i motstanderens halvdel.',
    'Feltskubber MÅ veltes først — før du kan ta baselinjekubbene.',
    'Etter alle kubber er veltet: kast på Kongen. Første lag til å velte Kongen vinner!',
    'Velter du Kongen for tidlig: laget ditt taper.',
  ],
  'molkky': [
    'Sett opp 12 nummererte kjegler (1–12) i trekantformasjon 3–4 m fra kastlinjen.',
    'Kast Mölkky-pinnen underhånds for å velte kjegler.',
    'Score: 1 kjegle = kjeglens tall. 2+ kjegler = antall veltede kjegler.',
    'Første til nøyaktig 50 poeng vinner. Overstiger du 50, faller scoren tilbake til 25.',
    'Tre misser på rad: spilleren er ute.',
  ],
  'disc-golf': [
    'Spill hvert hull ved å kaste disc fra tee mot kurven.',
    'Kast fra der disc landet til den er i kurven. Tell hvert kast som 1 slag.',
    'Par er vanligvis 3 slag per hull.',
    'Lavest totalt antall slag over alle hull vinner.',
  ],
  'cornhole': [
    '2 lag. Brett plasseres 9 m fra hverandre. Hvert lag har 4 poser i sin farge.',
    'Lag kaster annenhver pose per runde. Hull = 3 p, på brettet = 1 p.',
    'KANSELLERING: Trekk laveste lags poeng fra høyestes — bare differansen teller.',
    'Første lag til nøyaktig 21 vinner.',
  ],
}

const FULL_RULES_NO: Record<string, string[]> = {
  'maxi-yatzy': [
    'Spillerne tar turer med å kaste alle 6 terningene.',
    'Etter hvert kast kan du sette til side terninger og kaste resten — opp til 3 kast totalt.',
    'Etter siste kast velger du én ufylt kategori å score i.',
    'ØVRE SEKSJON: Ettere til Seksere — summer matchende terninger. 100 bonuspoeng hvis øvre sum ≥ 84.',
    'NEDRE SEKSJON:',
    '  1 Par: sum av høyeste par',
    '  2 Par: sum av to par',
    '  3 Par: sum av tre par',
    '  3 Like: sum av tre like terninger',
    '  4 Like: sum av fire like terninger',
    '  5 Like: sum av fem like terninger',
    '  Liten Straight (1-2-3-4-5): 15 poeng',
    '  Stor Straight (2-3-4-5-6): 20 poeng',
    '  Full Straight (1-2-3-4-5-6): 21 poeng',
    '  Hytte (2+3 like): sum av alle terninger',
    '  Hus (3+3 like): sum av alle terninger',
    '  Tårn (2+4 like): sum av alle terninger',
    '  Sjanse: sum av alle terninger',
    '  Maxi Yatzy (alle 6 like): 100 poeng',
    'Kan eller vil du ikke score en kategori, stryk den (0 poeng).',
    'Spillet slutter når alle har fylt alle kategorier. Høyeste totalscore vinner.',
  ],
  'yatzy': [
    'Kast 5 terninger opp til 3 ganger per tur.',
    'Etter hvert kast kan du beholde terninger og kaste resten.',
    'Score i én ufylt kategori etter siste kast.',
    'ØVRE SEKSJON (Ettere–Seksere): Summer alle matchende terninger. 50 bonuspoeng hvis sum ≥ 63.',
    'NEDRE SEKSJON:',
    '  1 Par: sum av høyeste par',
    '  2 Par: sum av to par',
    '  3 Like: sum av tre like terninger',
    '  4 Like: sum av fire like terninger',
    '  Fullt Hus (2+3): 25 poeng',
    '  Liten Straight (1-2-3-4 eller 2-3-4-5): 30 poeng',
    '  Stor Straight (1-2-3-4-5 eller 2-3-4-5-6): 40 poeng',
    '  Sjanse: sum av alle 5 terninger',
    '  Yatzy (alle 5 like): 50 poeng',
    'Stryk en kategori du ikke kan eller vil score (0 poeng).',
    'Spillet slutter når alle kategorier er fylt. Høyeste totalscore vinner.',
  ],
  'darts-501': [
    'Hver spiller begynner med 501 poeng.',
    'Spillerne kaster etter tur — 3 piler per tur.',
    'Poengsummen er summen av 3 piler, trukket fra nåværende score.',
    'Dobling: dobbelringen gir dobbel verdi. Trippel: trippelringen gir tredobbel verdi.',
    'Blink: ytre blink = 25, indre blink = 50.',
    'AVSLUTNING: For å vinne må du redusere scoren til nøyaktig 0.',
    '  Siste pil må treffe en dobling eller blink.',
    '  Bust (overskrider 0 eller ender på 1): scoren tilbakestilles til start av turen.',
    'Første til nøyaktig 0 vinner.',
  ],
  'darts-301': [
    'Samme regler som 501, men starter fra 301 — kortere og mer intens.',
    'Hver spiller begynner med 301 poeng.',
    'Spillerne kaster etter tur — 3 piler per tur.',
    'Trekk summen av 3 piler fra scoren din.',
    'For å vinne: reduser scoren til nøyaktig 0. Siste pil må treffe dobling eller blink.',
    'Bust (under 0 eller treffer 1): hele turen kanselleres — scoren tilbakestilles.',
  ],
  'darts-cricket': [
    'Tall i spill: 20, 19, 18, 17, 16, 15 og Blink (25/50).',
    'Hvert kast: 3 piler. Registrer merker per tall du treffer.',
    'Single = 1 merke, dobling = 2 merker, trippel = 3 merker. Ytre blink = 1, indre blink = 2.',
    'Lukk et tall ved å samle 3 merker.',
    'Etter lukking scorer ekstra merker poeng (ansiktsverdi per merke) — men bare mens minst én motstander ikke har lukket det.',
    'Blink scorer 25 p per merke ved scoring.',
    'VINNERBETINGELSE: Lukk alle tall OG ha en score lik eller høyere enn alle motstandere.',
    'Taktikk: lukk høye tall først for å maksimere scoringsmuligheter.',
  ],
  'hearts': [
    'Del alle kortene jevnt. Spillerne gir 3 kort til venstre før hver runde (retning roterer).',
    'Spilleren med 2 i kløver leder første stikk.',
    'Spillerne må følge farge hvis mulig. Kan de ikke, spilles et hvilket som helst kort.',
    'Høyeste kort av ledet farge vinner stikket. Vinneren leder neste.',
    'Hjerter kan ikke ledes før et hjertekort er "brutt" (spilt uten å kunne følge farge).',
    'POENG PER RUNDE:',
    '  Hvert hjertekort = 10 straffepoeng',
    '  Hjerteess = 20 straffepoeng',
    '  Spardam = 100 straffepoeng',
    '  Ruterknekt = −100 poeng',
    '  Alle andre kort = 0',
    '  Totalt delt ut per runde = 140 poeng',
    'SKYT MÅNEN (valgfri regel):',
    '  Tar én spiller ALLE hjertekort OG Spardam:',
    '  Den spilleren scorer 0 for runden, alle andre får 240 poeng.',
    'Registrer løpende totaler etter hver runde.',
    'SPILLSLUTT: Spillet slutter etter runden der en spiller når eller overstiger 500 poeng.',
    'Spilleren med LAVEST totalscore vinner.',
  ],
  'farkle': [
    'På din tur: kast alle 6 terningene.',
    'SCOREKOMBINASIONER:',
    '  Enkelt 1 = 100 poeng',
    '  Enkelt 5 = 50 poeng',
    '  Tre ettere = 1000 poeng',
    '  Tre toere = 200 poeng',
    '  Tre treere = 300 poeng',
    '  Tre firere = 400 poeng',
    '  Tre femmere = 500 poeng',
    '  Tre seksere = 600 poeng',
    '  Fire like = dobbelt av tre-like-score',
    '  Fem like = tredobbelt av tre-like-score',
    '  Seks like = 3000 poeng',
    '  Straight 1-2-3-4-5-6 = 1500 poeng',
    '  Tre par = 1500 poeng',
    'FARKLE: Scorer ingen terninger = Farkle — mister alle ubankede poeng for turen.',
    'VARME TERNINGER: Alle 6 scorer i ett kast — kast alle 6 igjen og legg til.',
    'BANKING: Etter scoring kan du banke poengene eller kaste gjenværende terninger.',
    'ÅPNING: Trenger minst 1000 poeng i én tur for å åpne kontoen.',
    'VINNER: Første til 10 000 utløser siste runde — alle andre får én tur til.',
    'Spilleren med høyest score (minst 10 000) etter siste runde vinner.',
  ],
  'spades': [
    'Del alle 52 kort (13 til hver). Spillerne ser på kortene og byr individuelt.',
    'By: anslå stikk du vil ta. Laveste by er 1 (eller Nil = 0, verdt +100/−100).',
    'Lagets by = summen av begge partnernes bud.',
    'Spar er alltid trumf. Led hvilken som helst farge (spar kan ikke ledes før brutt).',
    'Høyeste kort av ledet farge vinner, med mindre trumfet. Vinner leder neste.',
    'POENGGIVNING: Laget når budet: 10 × budt stikk. Hvert overtrekk (pose): +1 p.',
    'For hver 10 poser akkumulert: −100 p.',
    'Laget når ikke budet: −10 × budt stikk.',
    'Nil-by: +100 p ved suksess, −100 p ved feil (partnerens by teller fortsatt).',
    'Første lag til 500 p vinner. Når begge lag 500 i samme runde, vinner høyest score.',
  ],
  'rummy': [
    'Del 7 kort (2–4 spillere) eller 10 kort (2 spillere). Resten danner trekkbunken; vend ett kort til startbunken.',
    'På din tur: trekk fra kortstokken eller kastebunken, deretter kast ett kort.',
    'KOMBINASJONER: Grupper = 3–4 kort av samme rang. Rekker = 3+ påfølgende kort av samme farge.',
    'Du kan legge til kort på eksisterende kombinasjoner på bordet.',
    'GÅ UT: Når du kan legge ned alle gjenværende kort (med ett kast), legg ned og kast siste kort.',
    'POENGGIVNING: Alle andre scorer straffepoeng for kort på hånden.',
    'Tallkort = pålydende, bildekort (J/Q/K) = 10 p, ess = 1 p.',
    'Løpende total. Lavest score når en spiller når avtalt grense (f.eks. 100) vinner.',
  ],
  'gin-rummy': [
    'Del 10 kort til hver. Vend ett kort til startbunken.',
    'Trekk fra kortstokken eller kastebunken, deretter kast ett kort.',
    'BANK: Når ubrukte (ulagte) kort summerer til 10 eller mindre, bank ved å kaste kortside ned.',
    'Motstanderen legger av kort på dine kombinasjoner, teller deretter gjenværende ubrukte.',
    'POENGGIVNING: Bankeren scorer (motstanderens ubrukte − bankerens ubrukte).',
    'GIN: Bank med 0 ubrukte → score alle motstanderens ubrukte + 25 bonus.',
    'UNDERKUTT: Hvis motstanderens ubrukte ≤ bankerens etter avlegging → motstanderen scorer differansen + 25.',
    'Spill til 100 p. Vinner scorer 25 spillbonus + 25 per vunnet hånd.',
  ],
  'canasta': [
    'Del 11 kort til hver. Resten danner trekkbunken; vend ett kort til startbunken.',
    'KOMBINASJONER: 3+ kort av SAMME RANG (ikke rekker/straighter). Legg dem åpent på bordet.',
    'VILLE KORT: Jokere (50 p) og 2-ere (20 p) kan erstatte hvilken som helst rang — men ville kort må aldri være i flertall mot naturlige kort i samme kombinasjon.',
    'CANASTA: Når en kombinasjon når 7 kort, blir det en canasta — brett den sammen til en stabel. Naturlig (uten jokere) = 500 p, Blandet (med jokere) = 300 p.',
    'GÅ UT: På din tur, legg ned / kvitt alle gjenværende kort (med ett kast til slutt). Laget MÅ ha minst én canasta først. Bonus: +100 p.',
    'RUNDEPOENG: Sum av kortverdier i kombinasjoner, minus kort igjen på hånden, pluss canastabonus.',
    'Kortverdier: Joker = 50, 2 = 20, Ess = 20, 8–K = 10, 4–7 = 5, Svart 3 = 5.',
    'Minimumskrav for første kombinasjon øker med score (0–1499: 50 p, 1500–2999: 90 p, 3000+: 120 p).',
    'Første lag til 5000 p vinner.',
  ],
  'phase-10': [
    'Del 10 kort. Trekk fra kortstokken eller kastebunken; kast ett kort per tur.',
    'FASER (må fullføres i rekkefølge): 1: 2 grupper à 3. 2: 1 gruppe à 3 + 1 rekke à 4. 3: 1 gruppe à 4 + 1 rekke à 4. 4: 1 rekke på 7. 5: 1 rekke på 8. 6: 1 rekke på 9. 7: 2 grupper à 4. 8: 7 kort av én farge. 9: 1 gruppe à 5 + 1 gruppe à 2. 10: 1 gruppe à 5 + 1 gruppe à 3.',
    'Jokere (J) kan erstatte et hvilket som helst kort. Skip-kort (S) gjør at neste spiller mister en tur.',
    'LEGG NED: Når hånden inneholder nåværende fase, legg den åpent på bordet din tur.',
    'Etter nedlegging kan du spille gjenværende kort på hvilken som helst fase på bordet.',
    'POENGGIVNING: Når noen går ut, scorer alle andre straffepoeng for kort på hånden (tallkort = pålydende, jokere/skip = 25 p).',
    'Spillere som fullførte fasen går til neste. Andre gjentar samme fase.',
    'Etter alle 10 faser (eller avtalte runder), lavest score vinner.',
  ],
  'uno': [
    'Del 7 kort. Vend øverste kort til startbunken.',
    'På din tur: spill ett matchende kort (samme farge, tall eller symbol). Kan du ikke, trekk ett — spill det hvis mulig, ellers behold det.',
    'HANDLINGSKORT: Hopp (neste spiller mister tur), Snu (retning endres), Trekk 2 (neste trekker 2 og mister tur).',
    'WILD-KORT: endre farge til hva som helst. Wild Trekk 4: endre farge OG neste trekker 4 (spill bare hvis du mangler matchende farge).',
    'UNO: Ropa "UNO!" når du spiller nest siste kort. Blir du tatt uten å ha ropt, trekk 2.',
    'POENGGIVNING: Når en spiller går ut, telles kort i alle andres hender.',
    'Tallkort = pålydende, handlingskort = 20 p, Wild/Wild Trekk 4 = 50 p.',
    'Løpende total. Første til 500 p avslutter spillet. Lavest score vinner.',
  ],
  'cabo': [
    'Del 4 kort ned til hver spiller. Kikk på dine to nederste kort.',
    'På din tur: vend øverste kort fra trekkbunken. Enten bytt det mot et av dine (kast gammelt) eller kast det.',
    'SPESIALEFFEKTER (ved kasting): 7/8 = kikk på et av dine egne. 9/10 = kikk på motstanderens. J/Q = bytt ett av dine med motstanderens (blindt). K (svart) = bytt fritt (kan se på eget). K (rødt) = ingen effekt.',
    'CABO: En spiller kan rope "Cabo" i stedet for å trekke. Alle andre får én tur til.',
    'AVSLØRING: Alle kort vendes. Lavest sum vinner runden.',
    'POENGGIVNING: Taperne scorer verdien av hånden. Den som ropte Cabo: scorer 0 hvis lavest eller likt; ellers +5 straff.',
    'Ess = 1, tallkort = pålydende, J/Q = 11/12, K = 13, Joker = −1.',
    'Løpende. Første til 100 p er ute. Siste gjenværende (eller lavest ved avtalt slutt) vinner.',
  ],
  'cribbage': [
    'Del 6 kort (5 i 3–4-spillerspill). Alle kaster 2 til kribben. Vend et startkort.',
    'PEGGING (spillfase): spill kort om hverandre, summer løpende. Score: nå 15 = 2 p, nå 31 = 2 p (eller 1 p for "go"). Par = 2 p, trilling = 6, firer = 12. Rekke på 3+ = antall kort i rekken.',
    'TELLING (visefase): tell hånden + startkortet, deretter teller utdeleren kribben.',
    'Poeng: 15-ere = 2 p per, par = 2 p, rekker = rekkens lengde, flush (4+ like farge) = 4–5 p, knave (knekt av startfarge på hånden) = 1 p.',
    'Første spiller til å nå 121 vinner umiddelbart (selv midt i en hånd).',
  ],
  'doppelkopf': [
    '48-korts kortstokk (uten 2–8). Del 12 kort til hver.',
    'LAG: De to spillerne med kloverkonnene er "Re"-laget; de andre er "Kontra". (I solospill spiller én mot alle.)',
    'TRUMFREKKEFØLGE (høyest til lavest): Q♣ Q♠ Q♥ Q♦ J♣ J♠ J♥ J♦ A♦ 10♦ K♦ 9♦ 8♦.',
    'Deretter vanlige farger (A 10 K 9 8).',
    'STIKKSPILL: Led et hvilket som helst kort. Andre må følge farge; kan de ikke, spilles hva som helst. Høyeste trumf vinner; ellers høyeste av ledet farge.',
    'POENGGIVNING: Tell kortpoeng i vunnede stikk. A=11, 10=10, K=4, Q=3, J=2, øvrige=0. Totalt = 240.',
    'Re vinner ved ≥121. Begge lag scorer spillpoeng basert på margin og bonuser.',
  ],
  'skat': [
    '32-korts kortstokk (7–A i alle farger). Del 10 kort; 2 skjulte kort danner skaten.',
    'BUDRUNDE: Spillerne byr spillverdier (18, 20, 22...). Høyeste budgiver blir deklaranten.',
    'SKAT: Deklaranten tar opp skaten, kaster 2 kort ned, erklærer: fargehånd, grand (bare knekter er trumf) eller null (unngå alle stikk).',
    'KNEKTER: I farge/grand-spill er alle fire knekter de høyeste trumfene (♣J høyest).',
    'STIKKSPILL: 10 stikk. Følg farge; kan du ikke, spill hva som helst. Knekter slår alle fargekort.',
    'KORTVERDIER: A=11, 10=10, K=4, Q=3, J=2. Øvrige = 0. Totalt = 120.',
    'POENGGIVNING: Deklaranten trenger 61 p (eller 31 ved null). Spillverdi = grunnverdi × multiplikatorer.',
    'Vinn: legg til spillverdi. Tap: trekk fra dobbel spillverdi.',
  ],
  'catan': [
    'Sett opp øya med heksagonale brikker; plasser startbosetninger og veier.',
    'Hvert kast: kast 2 terninger. Alle spillere samler ressurser fra hekser med det kastet tall, tilstøtende bosetninger/byer.',
    '7 = røveren flyttes: ingen ressurser for det tallet; røverspilleren stjeler 1 kort fra spiller ved ny plassering.',
    'BYGG: Vei = Tre + Leire. Bosetning = Tre + Leire + Korn + Sau. By (oppgradering) = 3 Malm + 2 Korn. Kortkjøp = Malm + Korn + Sau.',
    'HANDEL: 4:1 med banken, 3:1 ved generell havn, 2:1 ved spesifikk havn, eller bytt med andre spillere.',
    'UTVIKLINGSKORT: Ridder (flytt røver + stjel), Seierpoeng, Veikonstruksjon, Overflod, Monopol.',
    'SPESIELT: Lengste vei (5+ sammenhengende) = 2 sp. Største hær (3+ riddere) = 2 sp.',
    'VINN: Nå 10 seierpoeng på din tur.',
  ],
  'ticket-to-ride': [
    'Hver spiller starter med 45 tog, 4 togkort og 3 destinasjonskort (behold minst 2).',
    'På din tur: trekk 2 togkort (fra bunke eller åpne kort), krev en rute (legg ned matchende kort) eller trekk destinasjonskort.',
    'KREV RUTE: Legg ned nøyaktig antall kort som matcher rutens farge. Grå ruter aksepterer én hvilken som helst farge.',
    'RUTEPOENG: 1 tog = 1, 2 = 2, 3 = 4, 4 = 7, 5 = 10, 6 = 15.',
    'DESTINASJONSKORT: Koble to byer → legg til bonuspoeng. Mislykkes → trekk fra poeng.',
    'SPILLSLUTT: Når en spiller har ≤2 tog, får alle (inkl. den spilleren) én siste tur.',
    'BONUS: Lengste sammenhengende rute = 10 p.',
    'Høyest score vinner.',
  ],
  'carcassonne': [
    'Hver spiller har 7 brikker. På din tur: trekk en flis, plasser den (kanter må matche), legg eventuelt en brikke.',
    'FUNKSJONER: By (omgitt av murer), Vei (slutter ved by/veikryss/blindvei), Kloster (omgitt av 8 fliser), Jordbruk (gressareal).',
    'BRIKKEPLASSERING: Plasser på hvilken som helst ufylt funksjon på flisen du nettopp la.',
    'POENGGIVNING (fullstendige funksjoner under spillet): By = 2 p/flis + 2 p/skjold. Vei = 1 p/flis. Kloster = 9 p (flis + alle 8 rundt).',
    'Flere spillere på samme funksjon (via utvidelse): alle scorer.',
    'SLUTT-POENG: Ufullstendig by = 1 p/flis + 1 p/skjold. Ufullstendig vei = 1 p/flis. Ufullstendig kloster = 1 + tilstøtende fliser. Jordbruk: 3 p per fullstendig tilstøtende by.',
    'Høyest score vinner.',
  ],
  'scrabble': [
    'Hver spiller trekker 7 brikker. Det første ordet må krysse midtfeltet.',
    'Hvert ord må leses venstre-til-høyre eller topp-til-bunn og kobles til eksisterende brikker.',
    'Alle nye ord dannet (inkl. kryssord) scores i samme tur.',
    'BRIKKER-VERDIER: Blank = 0, A/E/I/O/U/L/N/S/T/R = 1, D/G = 2, B/C/M/P = 3, F/H/V/W/Y = 4, K = 5, J/X = 8, Q/Z = 10.',
    'PREMIEFELTER: DL = dobbelt bokstav, TL = trippelt bokstav, DW = dobbelt ord, TW = trippelt ord.',
    'Premiefelter gjelder kun første gang en brikke dekker dem.',
    'BINGO: Bruke alle 7 brikker i ett trekk = +50 bonuspoeng.',
    'AVSLUTNING: Når posen er tom og én spiller bruker alle brikker, eller alle passer to ganger.',
    'Alle trekker fra pålydende av ubrukte brikker. Den som gikk ut legger til andres fradrag i sin score.',
    'Høyest totalscore vinner.',
  ],
  'backgammon': [
    'Hver spiller har 15 brikker. Startoppsett er fastsatt. Hvit beveger seg med klokken, svart mot klokken.',
    'FLYTTE: Kast 2 terninger; flytt brikker nøyaktig det antall vist. Dobbelt = spill hvert terning to ganger (4 trekk totalt).',
    'BLOKKERTE PUNKTER: Du kan ikke lande på et punkt med 2+ motstanderbrikker.',
    'TREFFE: Lander du på et punkt med nøyaktig 1 motstanderbrikke (blot) → send den til baren.',
    'BAR: En spiller med brikker på baren MÅ sette dem inn i motstanderens hjemmebrett først.',
    'BÆRE AV: Når alle brikker er i hjemmefeltet (punkt 1–6), begynn å bære av. Kast et tall → fjern brikke fra det punktet (eller høyere hvis tomt).',
    'DOBLINGSTERNING (valgfritt): Ved starten av din tur, tilby å doble innsatsen. Motstanderen kan godta eller gi seg.',
    'GAMMON: Vinner før motstanderen bærer av noen → dobbelt innsats. Backgammon: vinner mens motstanderen har brikker på bar eller i ditt hjemmebrett → trippel innsats.',
  ],
  'sequence': [
    'Brettet viser alle 52 kort to ganger (uten knekter). Hjørnefelter er fri (joker for alle).',
    'På din tur: spill et kort, plasser din brikke på matchende felt, kast, trekk ett nytt kort.',
    'KNEKTER: Enøyde knekter (♠J, ♥J) = fjern en motstanderbrikke. Toøyde knekter (♦J, ♣J) = plasser på et ledig felt.',
    'DØDT KORT: Alle matchende felt er blokkert — kast og trekk uten å plassere.',
    'SEKVENSER: 5 på rad av din farge. Hjørne-jokerfelter teller for alle.',
    'VINN: 2 lag: 2 sekvenser hver; 3 lag: 1 sekvens. Spor sekvenser. Første til målet vinner.',
  ],
  'petanque': [
    'Lag: 1v1 (3 kuler), 2v2 (3 kuler) eller 3v3 (2 kuler). Kast cochonneten (målet) 6–10 meter.',
    'Lag kaster annenhver gang. Laget uten nærmeste kule kaster til de leder eller går tomme.',
    'PEKE: Kast for å komme nær. SKYTE: Kast for å treffe motstanderkule vekk.',
    'SLUTT PÅ RUNDE (mène): Når alle kuler er kastet, scorer laget med nærmeste kule.',
    'Poeng = antall av dine kuler nærmere målet enn motstanderens nærmeste kule.',
    'Første til 13 poeng vinner kampen.',
    'Ingen lag når 13 etter avtalte runder: høyest score vinner.',
  ],
  'croquet': [
    'Standard assosiasjonskrokket: hvert lag har 2 baller. Fullfør 12 ringer (6 i hver retning) + pelen i rekkefølge.',
    'SLAG: Hvert kast starter med 1 slag. Passere en ring = 1 bonusslag. Roquet (treffe annen ball) = 2 bonusslag.',
    'KROKKETSLAG: Etter roquet, plasser ballen din inntil den andres. Slå ballen din for å flytte begge.',
    'FORTSETTELSE: Etter krokketslaget får du 1 fortsettelsesslag.',
    'Hver ball kan roquetes én gang per tur (tilbakestilles etter å ha passert en ring).',
    'VINN: Første lag til å kjøre alle ringer og treffe pelen med begge baller.',
    'HAGEVERSJON: forenklede regler — 1 poeng per ring, første til avtalt total vinner.',
  ],
  'bowling': [
    '10 frames per spill. I hvert frame: kast opp til 2 ganger.',
    'STRIKE (X): Alle 10 kjegler på første kast. Score = 10 + sum av neste 2 kast.',
    'SPARE (/): Alle gjenværende kjegler på andre kast. Score = 10 + neste kast.',
    'ÅPENT FRAME: Verken strike eller spare. Score = veltede kjegler.',
    '10. FRAME: Strike gir 2 ekstra kast. Spare gir 1 ekstra kast. Ellers kun 2 kast.',
    'PERFEKT SPILL: 12 strikes på rad = 300 poeng.',
    'Høyest score vinner.',
  ],
  'table-tennis': [
    'SETT: Første til 11 poeng, vinn med 2. Ved 10-10 (deuce) byttes serve etter hvert poeng til noen leder med 2.',
    'SERVE: Ball kastes 16 cm opp, slås så den spretter på serverens side, passerer nettet og spretter på mottakerens side.',
    'POENGGIVNING: Poeng gis når motstanderen ikke returnerer ballen korrekt.',
    'KAMP: Best av 3 (første til 2 sett) eller best av 5 (første til 3 sett). Sider byttes etter hvert sett.',
    'I sett 5 (eller 3 i best av 3) bytter spillerne sider ved 5 poeng.',
  ],
  'billiards': [
    '8-BALL: Hver spiller tar én gruppe (solide 1–7 eller striper 9–15). Sett inn alle, deretter 8-ballen.',
    'BREAK: Legg ut 15 baller. Breakeren må treffe bunken og enten sette inn en ball eller drive 4 baller til kanten.',
    'ÅPENT BORD: Etter break er bordet "åpent" til første ball er satt inn (bestemmer grupper).',
    'FOUL: Setter inn køballen, treffer ikke egne baller først, ingen ball når kanten etter kontakt. Motstanderen får ball-in-hand.',
    'VINN: Sett inn 8-ballen når gruppen er tømt. Meld lomme for 8-ballen.',
    'TAP: Setter inn 8-ballen før gruppen er tømt, eller rammer 8-ballen ved break.',
    'Spor frames (individuelle kamper) vunnet. Flest frames vinner sesjonen.',
  ],
  'badminton': [
    'POENGGIVNING: Rally-scoring — poeng deles ut etter hvert rally, uansett hvem som servet.',
    'SETT: Første til 21 poeng, vinn med 2. Ved 29-29 vinner første til 30.',
    'KAMP: Best av 3 sett. Sider byttes etter hvert sett, og i sett 3 når første spiller når 11.',
    'SERVE: Server og mottaker står i diagonalt motstående servefelt. Serve må slås under livet.',
    'I SPILL: Fjederballen må passere over nettet og lande innenfor banemarkingene.',
    'FEIL: Ball lander ute, treffer nettet, spiller berører nettet, ball fanges. Poeng til motstander.',
  ],
  'foosball': [
    'SERVE: Ballen serves gjennom sideåpningen til midtstangen. Spillet starter umiddelbart.',
    'SCORING: Mål teller hvis ballen krysser mållinjen helt. Sparkede tilbake mål teller.',
    'SPINNING: Spillere kan ikke rotere en stang 360° før eller etter ballkontakt (husregler varierer).',
    'DØD BALL: Hvis ballen stopper der ingen stang når, serves på nytt.',
    'KAMP: Vanlige formater — først til 5 mål, 10 mål, eller tidsbegrenset. Best av 3 eller 5 kamper.',
    'Spor mål per kamp og kamper vunnet for å avgjøre matchvinneren.',
  ],
  'kubb': [
    'Oppsett: 5 kubber på hver baselinje, Kongen i midten. Bane 5×8 m (kan gjøres mindre).',
    'KAST: Hvert lag kaster 6 kastepinner (underhånds) for å velte motstanderens kubber.',
    'FELTKUBBER: Veltede baselinjekubber kastes av motstanderen inn i angriperens halvdel.',
    'PRIORITET: Hvis feltkubber står igjen, MÅ angrepslaget velte dem før baselinjekubbene.',
    'Feltkubber som lander utenfor banen plasseres 1 meter fra Kongen.',
    'FORDELSLINJE: Hvis feltkubber finnes, kan angrepslaget rykke frem til nærmeste feltkubb.',
    'VINNERBETINGELSE: Velt alle motstanderkubber (felt + baselinje), deretter Kongen.',
    'STRAFF: Velter du Kongen før alle kubber er nede = øyeblikkelig tap.',
    'Lag bytter tur. Flest seire over avtalte kamper vinner.',
  ],
  'molkky': [
    'Oppsett: 12 kjegler (1–12) i trekantformasjon, 3–4 meter fra kastlinjen.',
    'På din tur: kast Mölkky-pinnen underhånds fra bak kastlinjen.',
    'POENGGIVNING: Nøyaktig 1 kjegle velter = score kjeglens tall. 2 eller flere velter = antall veltede kjegler.',
    'Kjegler settes opp igjen der de falt etter hvert kast (de sprer seg utover).',
    'MÅL: Nå nøyaktig 50 poeng.',
    'OVERSKRIDELSE: Score over 50 → faller tilbake til 25.',
    'TRE MISSER: Velt ingen kjegler 3 turer på rad → spilleren er eliminert.',
    'Vinneren er den første til nøyaktig 50 poeng.',
  ],
  'disc-golf': [
    'Hvert hull starter ved en oppmalt tee. Kast mot målkurven.',
    'Etter hvert kast gjøres neste kast fra der disc landet.',
    'Hullet er fullført når disc lander og blir i metallkurven.',
    'POENGGIVNING: Tell hvert kast. Under par = birdie (−1), eagle (−2). Over par = bogey (+1).',
    'Ut av bane (OB): +1 straffeslag, kast fra der disc gikk OB (eller anvist droppesone).',
    'Obligatoriske ruter (mandos): disc må passere riktig side av markør — ellers +1 slag.',
    'HANDIKAP: Valgfritt. Spillere trekker fra handikap fra total score.',
    'Lavest totalt antall slag etter alle hull vinner.',
  ],
  'cornhole': [
    'Oppsett: to brett 9 m fra hverandre. Hvert lag har 4 poser i sin farge.',
    'KASTING: Lag kaster annenhver pose fra samme side. Alle 4 poser per lag per runde.',
    'POENGGIVNING: Pose gjennom hullet = 3 p. Pose på brettet = 1 p. Pose som spretter opp = 0 p (fjernes).',
    'KANSELLERING: Etter runden trekkes laveste lags poeng fra høyestes — bare differansen legges til.',
    'Eksempel: Lag A scorer 7, Lag B scorer 4 → Lag A får 3 p den runden.',
    'VINN: Første lag til nøyaktig 21 poeng vinner.',
    'BUST (husregler): Over 21 nullstilles til 11 eller 15 — avtal på forhånd.',
  ],
}

export function getRules(gameId: string, locale: string): GameRules | undefined {
  const rules = RULES[gameId]
  if (!rules) return undefined
  if (locale === 'no') {
    const noQS = QUICK_START_NO[gameId]
    const noFull = FULL_RULES_NO[gameId]
    if (noQS || noFull) {
      return {
        quickStart: noQS ?? rules.quickStart,
        full: noFull ?? rules.full,
      }
    }
  }
  return rules
}
