export interface GameRules {
  quickStart: string[]
  full: string[]
}

export const RULES: Record<string, GameRules> = {
  'maxi-yatzy': {
    quickStart: [
      'Roll 6 dice up to 3 times per turn, keeping any dice between rolls.',
      'Score in any empty category — each category can only be used once.',
      'Upper section (Ones–Sixes): score matching dice. Bonus of 100 pts if sum ≥ 84.',
      'Lower section: 1 Pair, 2 Pairs, 3 Pairs, 3/4/5 of a Kind, Straights, House (2+3), Full House (3+3), Tower (2+4), Chance, Maxi Yatzy (100 pts).',
      'Highest total score wins.',
    ],
    full: [
      'Each player takes turns rolling all 6 dice.',
      'After each roll you may set aside any dice and re-roll the rest — up to 3 rolls total.',
      'After your final roll, choose one unfilled category to score in.',
      'UPPER SECTION: Ones through Sixes — total the matching dice. Score 100 bonus if upper sum ≥ 84.',
      'LOWER SECTION:',
      '  1 Par: sum of highest pair',
      '  2 Par: sum of two pairs',
      '  3 Par: sum of three pairs',
      '  3 Like: sum of three matching dice',
      '  4 Like: sum of four matching dice',
      '  5 Like: sum of five matching dice',
      '  Liten Straight (1-2-3-4-5): 15 points',
      '  Stor Straight (2-3-4-5-6): 20 points',
      '  Full Straight (1-2-3-4-5-6): 21 points',
      '  House (2+3 of a kind): sum of all dice',
      '  Full House (3+3 of a kind): sum of all dice',
      '  Tower (2+4 of a kind): sum of all dice',
      '  Chance: sum of all dice',
      '  Maxi Yatzy (all 6 same): 100 points',
      'If you cannot or do not want to score a category, you must cross it out (score 0).',
      'Game ends when all players have filled every category. Highest total wins.',
    ],
  },
  'yatzy': {
    quickStart: [
      'Roll 5 dice up to 3 times per turn, keeping any dice between rolls.',
      'Score in any empty category — each can only be used once.',
      'Upper section (Ones–Sixes): score matching dice. Bonus of 50 pts if sum ≥ 63.',
      'Lower section: 1 Pair, 2 Pair, 3/4 of a Kind, Full House, Small/Large Straight, Chance, Yatzy (50 pts).',
      'Highest total wins.',
    ],
    full: [
      'Roll 5 dice up to 3 times per turn.',
      'After each roll you may keep any dice and re-roll the rest.',
      'Score in one unfilled category after your final roll.',
      'UPPER SECTION (Ones–Sixes): Score the total of all matching dice. 50 bonus points if upper section total ≥ 63.',
      'LOWER SECTION:',
      '  1 Pair: sum of highest pair',
      '  2 Pair: sum of two pairs',
      '  3 of a Kind: sum of three matching dice',
      '  4 of a Kind: sum of four matching dice',
      '  Full House (2+3): 25 points',
      '  Small Straight (1-2-3-4 or 2-3-4-5): 30 points',
      '  Large Straight (1-2-3-4-5 or 2-3-4-5-6): 40 points',
      '  Chance: sum of all 5 dice',
      '  Yatzy (all 5 same): 50 points',
      'Cross out any category you cannot or choose not to score (0 points).',
      'Game ends when all categories are filled. Highest total wins.',
    ],
  },
  'darts-501': {
    quickStart: [
      'Each player starts with 501 points.',
      'Take turns throwing 3 darts each. Subtract your score from your total.',
      'You must finish on exactly 0 — the finishing dart must land in a double (or bullseye).',
      'If you go below 0, or land exactly on 1, your turn is a "bust" — your score resets to what it was before your throw.',
      'First player to reach exactly 0 wins.',
    ],
    full: [
      'Each player begins with 501 points.',
      'Players alternate turns throwing 3 darts at the board.',
      'Score is the total of the 3 darts, subtracted from your current score.',
      'Doubles: doubles ring scores double the segment value.',
      'Trebles: treble ring scores triple the segment value.',
      'Bull: outer bull = 25, inner bull (bullseye) = 50.',
      'CHECKOUT: To win, you must reduce your score to exactly 0.',
      '  The final dart must land in a double or the bullseye.',
      '  If you cannot checkout or overshoot, your turn is a "bust" — score returns to start of that turn.',
      '  If your score reaches 1, it is a bust (cannot check out on 1).',
      'First player to reach exactly 0 wins.',
    ],
  },
  'hearts': {
    quickStart: [
      '3–6 players, standard 52-card deck (remove low cards to make it divide evenly).',
      'Each trick: highest card of the led suit wins. Hearts have no trump.',
      'SCORING: Hearts = 10 pts each (Ace of Hearts = 20 pts), Queen of Spades = 100 pts, Jack of Diamonds = −100 pts.',
      'Shooting the moon (optional): take ALL hearts + Queen of Spades → you score 0, everyone else gets 240 pts.',
      'Game ends when someone reaches 500 points. Lowest score wins.',
    ],
    full: [
      'Deal all cards evenly. Players pass 3 cards to the left before each round (direction rotates).',
      'The player with the 2 of Clubs leads the first trick.',
      'Players must follow suit if they can. If unable, play any card.',
      'The highest card of the led suit wins the trick. The winner leads next.',
      'Hearts cannot be led until a heart has been "broken" (played when unable to follow suit).',
      'SCORING PER ROUND:',
      '  Each heart = 10 penalty points',
      '  Ace of Hearts = 20 penalty points',
      '  Queen of Spades (Spar dame) = 100 penalty points',
      '  Jack of Diamonds (Ruter knekt) = −100 points',
      '  All other cards = 0',
      '  Total points distributed per round = 140',
      'SHOOTING THE MOON (optional rule):',
      '  If one player takes ALL hearts AND the Queen of Spades:',
      '  That player scores 0 for the round, all other players receive 240 points.',
      'Record running totals after each round.',
      'GAME END: The game ends after the round in which a player reaches or exceeds 500 points.',
      'The player with the LOWEST total score wins.',
    ],
  },
  'darts-301': {
    quickStart: [
      'Each player starts with 301 points.',
      'Take turns throwing 3 darts. Subtract your score from your total.',
      'You must finish on exactly 0 — the finishing dart must land in a double (or bullseye).',
      'If you bust (go below 0 or land on 1), your score resets to before your throw.',
      'First player to reach exactly 0 wins.',
    ],
    full: [
      'Same rules as 501, but starting from 301 — games are shorter and more intense.',
      'Each player begins with 301 points.',
      'Players alternate turns throwing 3 darts.',
      'Subtract your 3-dart total from your score each turn.',
      'To win, reduce your score to exactly 0. The final dart must land on a double or bullseye.',
      'Busting (going below 0 or hitting 1) cancels the entire turn — score returns to start of that turn.',
    ],
  },
  'darts-cricket': {
    quickStart: [
      'Numbers in play: 15, 16, 17, 18, 19, 20, and Bull.',
      'Hit a number 3 times to "close" it. Marks: 1 hit = /, 2 hits = X, 3 hits = closed (⊗).',
      'Once you\'ve closed a number, extra hits score points — but only if your opponent hasn\'t closed it too.',
      'Win by closing all numbers AND having the highest (or equal) score.',
    ],
    full: [
      'Numbers in play: 20, 19, 18, 17, 16, 15, and Bull (25/50).',
      'Each turn: throw 3 darts. Record marks on each number hit.',
      'Singles = 1 mark, doubles = 2 marks, triples = 3 marks. Outer bull = 1 mark, inner bull = 2 marks.',
      'Close a number by accumulating 3 marks on it.',
      'Scoring: if you close a number, extra marks score points (face value per mark), but only while at least one opponent hasn\'t closed it.',
      'Bull scores 25 pts per mark when scoring.',
      'WIN CONDITION: be the first to close all numbers AND have a score equal to or higher than all opponents.',
      'Strategy: close high-value numbers first to maximise scoring opportunities.',
    ],
  },
  'spades': {
    quickStart: [
      '4 players, 2 teams of 2 sitting opposite each other.',
      'Each player bids how many tricks they expect to take. Spades are always trump.',
      'Score 10 pts per trick bid if your team meets its bid. Overtricks (bags) score 1 pt each but 10 bags = −100 pts.',
      'Underbidding costs 10 pts per trick short.',
      'First team to 500 pts wins.',
    ],
    full: [
      'Deal all 52 cards (13 each). Players look at their cards and bid individually.',
      'Bids: estimate tricks you will take. Minimum bid is 1 (or Nil = 0, worth +100/−100).',
      'Team bid = sum of both partners\' bids.',
      'Spades are always trump. Lead any suit (except spades cannot lead until broken).',
      'Highest card of led suit wins, unless trumped. Winner leads next.',
      'SCORING: If team makes their bid: 10 × bid points. Each overtrick (bag): +1 pt.',
      'Every 10 bags accumulated: −100 pts.',
      'If team fails bid: −10 × bid points.',
      'Nil bid: +100 pts if successful, −100 pts if failed (partner\'s bid still counts).',
      'First team to 500 pts wins. If both reach 500 in same round, higher score wins.',
    ],
  },
  'rummy': {
    quickStart: [
      'Draw a card each turn, then discard one. Aim to form sets (3+ of same rank) and runs (3+ consecutive same suit).',
      'Go out by melding all your cards (with or without one discard).',
      'Score penalty points equal to the face value of unmelded cards in opponents\' hands.',
      'Aces = 1 pt, face cards = 10 pts. Lowest score wins.',
    ],
    full: [
      'Deal 7 cards (2–4 players) or 10 cards (2 players). Remaining cards form the draw pile; flip one card to start discard pile.',
      'On your turn: draw from the deck or discard pile, then discard one card.',
      'MELDS: Sets = 3 or 4 cards of the same rank. Runs = 3+ consecutive cards of the same suit.',
      'You may lay off (add) cards to existing melds on the table.',
      'GO OUT: When you can meld all remaining cards (with one discard), place melds face-up and discard final card.',
      'SCORING: All other players score penalty points for cards in hand.',
      'Number cards = face value, face cards (J/Q/K) = 10 pts, Aces = 1 pt.',
      'Running total. Lowest score when a player reaches an agreed limit (e.g. 100) wins.',
    ],
  },
  'gin-rummy': {
    quickStart: [
      '2 players. Draw a card each turn, discard one. Form sets and runs.',
      'Knock when unmatched cards total 10 or less. Opponent lays off cards on your melds.',
      'Gin (0 unmatched): +25 bonus. Undercut (opponent scores ≤ yours): +25 pts to opponent.',
      'Highest score after agreed rounds wins.',
    ],
    full: [
      'Deal 10 cards each. Flip one card to start discard pile.',
      'Draw from deck or discard pile, then discard one card.',
      'KNOCK: When your unmatched (deadwood) cards total 10 or less, knock by discarding face-down.',
      'Opponent lays off cards onto your melds, then totals their remaining deadwood.',
      'SCORING: Knocker scores (opponent\'s deadwood − knocker\'s deadwood).',
      'GIN: Knock with 0 deadwood → score all of opponent\'s deadwood + 25 bonus.',
      'UNDERCUT: If opponent\'s deadwood ≤ knocker\'s after lay-offs → opponent scores difference + 25.',
      'Play to 100 pts. Winner scores 25 bonus (game bonus) + 25 per hand won (box bonus).',
    ],
  },
  'canasta': {
    quickStart: [
      '2–6 players (best with 4 in 2 teams). Form melds of 3+ cards of the same rank.',
      'A canasta is a meld of 7+ cards. Natural canasta = 7 natural cards (+500 pts).',
      'Wild cards (jokers + 2s) can substitute in melds but not exceed natural cards.',
      'First team to 5000 pts wins.',
    ],
    full: [
      'Deal 11 cards each. Form a draw pile; flip one card to start discard pile.',
      'MELDS: 3 or more cards of the same rank. Wild cards (jokers = 50 pts, 2s = 20 pts) may substitute but no more than natural cards in the meld.',
      'CANASTA: A meld of 7 cards. Natural canasta (no wilds) = 500 pts. Mixed canasta (with wilds) = 300 pts.',
      'GOING OUT: Meld all cards (team must have at least one canasta). Score bonus 100 pts.',
      'ROUND SCORING: sum of card values in melds, minus cards left in hand, plus bonuses.',
      'Card values: Joker = 50, 2 = 20, Ace = 20, 8–K = 10, 4–7 = 5, Black 3 = 5.',
      'INITIAL MELD requirement increases as score grows (0–1499: 50 pts, 1500–2999: 90 pts, 3000+: 120 pts).',
      'First team to 5000 pts wins.',
    ],
  },
  'phase-10': {
    quickStart: [
      'Complete 10 specific phases in order. Each phase is a combination of sets and/or runs.',
      'Draw a card, then discard. Complete your current phase by laying down the required cards.',
      'Once your phase is down, play off remaining cards on any laid-down phase.',
      'Penalty points for cards remaining when someone goes out. Fewest points after all 10 phases wins.',
    ],
    full: [
      'Deal 10 cards. Draw from deck or discard pile; discard one card each turn.',
      'PHASES (must be completed in order): 1: 2 sets of 3. 2: 1 set of 3 + 1 run of 4. 3: 1 set of 4 + 1 run of 4. 4: 1 run of 7. 5: 1 run of 8. 6: 1 run of 9. 7: 2 sets of 4. 8: 7 cards of one colour. 9: 1 set of 5 + 1 set of 2. 10: 1 set of 5 + 1 set of 3.',
      'Wild cards (W) can substitute any card. Skip cards (S) force the next player to lose a turn.',
      'LAY DOWN: Once your hand contains the current phase, lay it face-up on your turn.',
      'After laying down, play remaining cards on any table phase (yours or others\').',
      'SCORING: When someone goes out, all others score penalty pts for cards in hand (number cards = face value, wilds/skips = 25 pts).',
      'Players who completed their phase advance to the next. Others repeat same phase.',
      'After all 10 phases (or agreed rounds), lowest score wins.',
    ],
  },
  'uno': {
    quickStart: [
      'Match the top card of the discard pile by colour, number, or symbol.',
      'Draw 2 if you can\'t play. Shout "UNO!" when you have 1 card left.',
      'Special cards: Skip, Reverse, Draw 2, Wild, Wild Draw 4.',
      'When a player goes out, others score penalty pts equal to cards in hand. First to 500 ends the game — lowest score wins.',
    ],
    full: [
      'Deal 7 cards each. Flip top card to start discard pile.',
      'On your turn: play a matching card (same colour, number, or symbol). If unable, draw one — then play it if possible, otherwise keep it.',
      'ACTION CARDS: Skip (next player loses turn), Reverse (direction changes), Draw 2 (next player draws 2 and loses turn).',
      'WILD cards: change colour to any colour. Wild Draw 4: change colour AND next player draws 4 (only play if you have no matching colour).',
      'UNO: call "UNO!" when playing your second-to-last card. If caught not calling, draw 2.',
      'SCORING: When a player goes out, count cards in all other hands.',
      'Number cards = face value, action cards = 20 pts each, Wild/Wild Draw 4 = 50 pts each.',
      'Cumulative total. First player to reach 500 pts ends the game. Lowest score wins.',
    ],
  },
  'cabo': {
    quickStart: [
      'Each player has 4 face-down cards. You may peek at your bottom 2 cards at the start.',
      'Draw a card and either swap it with one of yours (discarding the old) or discard it (using any special ability).',
      'Call "Cabo" when you think your hand total is lowest. Everyone gets one more turn.',
      'Lowest total wins the round. First to 100 pts loses; lowest score wins.',
    ],
    full: [
      'Deal 4 cards face-down to each player. Peek at your own bottom 2 cards.',
      'On your turn: flip top of draw pile. Either swap it with any of your cards (discard old card) or discard it.',
      'SPECIAL ABILITIES (when discarding): 7/8 = peek at one of your own cards. 9/10 = peek at an opponent\'s card. J/Q = swap one of your cards with an opponent\'s (blind). K (black) = swap freely (you may look at your card). K (red) = no ability.',
      'CABO: Any player may call "Cabo" instead of drawing. All other players get one more turn.',
      'REVEAL: All cards are flipped. Lowest total wins the round.',
      'SCORING: Losing players score the value of their hand. Cabo caller: if lowest or tied, scores 0; if not lowest, +5 penalty.',
      'Aces = 1, number cards = face value, J/Q = 11/12, K = 13, Joker = −1.',
      'Cumulative. First to 100 pts is out. Last player standing (or lowest at agreed end) wins.',
    ],
  },
  'cribbage': {
    quickStart: [
      '2–4 players. Deal 6 cards; each player discards 2 to the "crib" (belongs to the dealer).',
      'The starter card is cut; if it\'s a Jack, dealer pegs 2 ("his heels").',
      'Play cards alternately, scoring for 15s, pairs, runs, and 31s. Then count your hand.',
      'First to 121 points wins.',
    ],
    full: [
      'Deal 6 cards (5 in 3–4 player game). Each player discards 2 to the crib. Cut a starter card.',
      'PEGGING (play phase): alternate playing cards, calling cumulative total. Score: reaching 15 = 2 pts, reaching 31 = 2 pts (or 1 pt for "go" if opponent can\'t play). Pairs = 2 pts, 3-of-a-kind = 6, four-of-a-kind = 12. Run of 3+ = pts equal to run length.',
      'COUNTING (show phase): count your hand + starter card, then dealer counts crib.',
      'Count scores: 15s = 2 pts each, pairs = 2 pts, runs = length of run, flush (4+ same suit) = 4–5 pts, nobs (Jack of starter suit in hand) = 1 pt.',
      'First player to peg to 121 wins immediately (even mid-hand).',
    ],
  },
  'doppelkopf': {
    quickStart: [
      '4 players, 2 teams (Re vs Kontra). Teams are secret — revealed by who holds the Queens of Clubs.',
      'Aim to win tricks worth 120+ points (Re) or to stop them (Kontra).',
      'Winning team scores 1 game point per player; bonuses for extra achievements.',
    ],
    full: [
      '48-card deck (no 2s–8s). Deal 12 cards each.',
      'TEAMS: The two players holding Queens of Clubs are "Re" team; others are "Kontra". (In solo games, one player plays alone.)',
      'TRUMP ORDER (highest to lowest): Q♣ Q♠ Q♥ Q♦ J♣ J♠ J♥ J♦ A♦ 10♦ K♦ 9♦ 8♦.',
      'Then plain suits (A 10 K 9 8) — no 7s.',
      'TRICK PLAY: Lead any card. Others must follow suit; if unable, play any card. Highest trump wins; if no trump, highest of led suit.',
      'SCORING: Count card points in won tricks. A=11, 10=10, K=4, Q=3, J=2, 9/8/7=0. Total = 240.',
      'Re wins if their total ≥ 121. Both teams score game points based on margin and bonuses (e.g. winning without opponents scoring = extra point).',
    ],
  },
  'skat': {
    quickStart: [
      '3 players. Deal 10 cards each with 2 cards face-down (the skat).',
      'Players bid to become the "declarer" who picks up the skat and names the trump suit.',
      'Declarer aims to win card points; defenders aim to stop them.',
    ],
    full: [
      '32-card deck (7–A in each suit). Deal 10 cards each; 2 cards face-down form the skat.',
      'BIDDING: Players bid game values (18, 20, 22...). Highest bidder becomes declarer.',
      'SKAT: Declarer picks up skat, discards 2 cards face-down, then declares: suit game, grand (only jacks trump), or null (avoid all tricks).',
      'JACKS: In suit/grand games, all four jacks are the highest trumps (♣ J highest).',
      'TRICK PLAY: 10 tricks. Follow suit; if unable, play any card. Jacks beat all suit cards.',
      'CARD VALUES: A=11, 10=10, K=4, Q=3, J=2. Others = 0. Total = 120.',
      'SCORING: Declarer must reach 61 pts (or 31 in null). Game value = base value × multipliers.',
      'Win: add game value to score. Lose: subtract double game value.',
    ],
  },
  'catan': {
    quickStart: [
      'Collect resources (Wood, Brick, Wheat, Sheep, Ore) to build roads, settlements, cities, and development cards.',
      'Settlements = 1 VP, Cities = 2 VP. Longest Road and Largest Army = 2 VP each.',
      'First player to 10 Victory Points wins.',
    ],
    full: [
      'Set up the island from hex tiles; place initial settlements and roads.',
      'Each turn: roll 2 dice. All players collect resources from hexes numbered with the roll adjacent to their settlements/cities.',
      '7 = robber moves: no resources produced for that number; robber player steals 1 card from a player adjacent to new robber location.',
      'BUILD: Road = Wood + Brick. Settlement = Wood + Brick + Wheat + Sheep. City (upgrade) = 3 Ore + 2 Wheat. Dev card = Ore + Wheat + Sheep.',
      'TRADE: 4:1 with bank, 3:1 at generic harbours, 2:1 at specific harbours, or trade with other players.',
      'DEV CARDS: Knight (move robber + steal), Victory Point, Road Building, Year of Plenty, Monopoly.',
      'SPECIAL: Longest Road (5+ consecutive roads) = 2 VP. Largest Army (3+ knights) = 2 VP.',
      'WIN: Reach 10 Victory Points on your turn.',
    ],
  },
  'ticket-to-ride': {
    quickStart: [
      'Claim railway routes by playing matching coloured train cards.',
      'Score points for routes claimed. Complete destination tickets (bonus) or fail them (penalty).',
      'When one player has 2 or fewer train pieces left, all players get one more turn, then score.',
    ],
    full: [
      'Each player starts with 45 trains, 4 train cards, and 3 destination tickets (keep at least 2).',
      'On your turn: draw 2 train cards (from deck or face-up), claim a route (play matching cards), or draw destination tickets.',
      'CLAIMING: Play the exact number of cards matching the route colour. Grey routes accept any single colour.',
      'ROUTE POINTS: 1 train = 1, 2 = 2, 3 = 4, 4 = 7, 5 = 10, 6 = 15.',
      'DESTINATION TICKETS: Connect two cities shown → add bonus points. Fail → subtract points.',
      'END GAME: When a player has ≤2 trains, all players (including them) get one final turn.',
      'BONUS: Longest continuous route = 10 pts.',
      'Highest score wins.',
    ],
  },
  'carcassonne': {
    quickStart: [
      'Take turns placing tiles to build a medieval landscape of cities, roads, and monasteries.',
      'Place a meeple (follower) on the tile to claim a feature. Score when features complete.',
      'At game end, score incomplete features and fields.',
    ],
    full: [
      'Each player has 7 meeples. On your turn: draw a tile, place it (must match edges), optionally place a meeple.',
      'FEATURES: City (surrounded by walls), Road (ends at city/crossroads/dead-end), Monastery (surrounded by 8 tiles), Field (grass area).',
      'MEEPLE PLACEMENT: Place on any unclaimed feature of the tile just placed.',
      'SCORING (completed features during game): City = 2 pts/tile + 2 pts/shield. Road = 1 pt/tile. Monastery = 9 pts (tile + all 8 surrounding).',
      'Multiple players on same feature (via expansion): all score.',
      'END GAME scoring: Incomplete city = 1 pt/tile + 1 pt/shield. Incomplete road = 1 pt/tile. Incomplete monastery = 1 + adjacent tiles. Fields: 3 pts per completed adjacent city.',
      'Highest score wins.',
    ],
  },
  'scrabble': {
    quickStart: [
      'Take turns placing letter tiles on the board to form words. Words must connect to existing tiles.',
      'Score = sum of letter values. Double/Triple Letter and Double/Triple Word squares multiply scores.',
      'Bingo (using all 7 tiles): +50 pts. Game ends when all tiles are used.',
      'Subtract unplayed tile values at end. Highest score wins.',
    ],
    full: [
      'Each player draws 7 tiles. The first word must cross the centre square.',
      'Each word must read left-to-right or top-to-bottom and connect to existing tiles.',
      'All new words formed (including cross-words) score on the same turn.',
      'TILE VALUES: Blank = 0, A/E/I/O/U/L/N/S/T/R = 1, D/G = 2, B/C/M/P = 3, F/H/V/W/Y = 4, K = 5, J/X = 8, Q/Z = 10.',
      'PREMIUM SQUARES: DL = double letter, TL = triple letter, DW = double word, TW = triple word.',
      'Premium squares only apply the first time a tile covers them.',
      'BINGO: Using all 7 tiles in one move = +50 bonus points.',
      'ENDING: When the bag is empty and one player uses all tiles, or all players pass twice.',
      'All players subtract face values of unplayed tiles. The player who finished adds others\' subtracted tiles to their score.',
      'Highest final score wins.',
    ],
  },
  'backgammon': {
    quickStart: [
      'Move all 15 pieces around the board into your home board, then bear them off.',
      'Roll 2 dice each turn; move pieces the shown numbers (can split between two pieces or use both on one).',
      'Hit a blot (single opponent piece) to send it to the bar; it must re-enter before other moves.',
      'First to bear off all pieces wins.',
    ],
    full: [
      'Each player has 15 checkers. Starting position is fixed. White moves clockwise, Black counter-clockwise.',
      'MOVING: Roll 2 dice; move checkers the exact number shown. Doubles = play each die twice (4 moves total).',
      'BLOCKED POINTS: You cannot land on a point holding 2+ opponent checkers.',
      'HITTING: Land on a point with exactly 1 opponent checker (blot) → send it to the bar.',
      'BAR: A player with checkers on the bar must enter them in the opponent\'s home board first.',
      'BEARING OFF: When all your checkers are in your home board (points 1–6), start bearing off. Roll a number → remove a checker from that point (or from a higher point if that point is empty).',
      'DOUBLING CUBE: Optional. At the start of your turn, offer to double the stakes. Opponent may accept or resign.',
      'GAMMON: Win before opponent bears off any → double the stake. Backgammon: win while opponent has a checker on bar or in your home board → triple the stake.',
    ],
  },
  'sequence': {
    quickStart: [
      '2–12 players (in 2 or 3 teams). Play a card from your hand and place a chip on the matching board space.',
      'Form a sequence of 5 chips in a row (horizontally, vertically, or diagonally).',
      'Jacks: one-eyed = remove an opponent chip; two-eyed = wild (play anywhere).',
      'First team to required sequences wins (1 team: 2 seq., 2 teams: 2 seq., 3 teams: 1 seq.).',
    ],
    full: [
      'The board shows all 52 cards twice (minus Jacks). Corner spaces are free (wildcards for all players).',
      'On your turn: play a card, place your chip on a matching space, discard, draw a new card.',
      'JACKS: One-eyed jacks (♠J, ♥J) = remove any opponent\'s chip. Two-eyed jacks (♦J, ♣J) = place on any empty space.',
      'DEAD CARD: If all matching spaces are blocked, discard and draw without placing.',
      'SEQUENCES: 5 in a row of your colour. Corner free spaces count for any player.',
      'WIN: Depending on player count — 2 teams need 2 sequences each; 3 teams need 1 sequence each.',
      'Track sequences made. Highest when game ends (or first to goal) wins.',
    ],
  },
  'petanque': {
    quickStart: [
      'Teams throw metal balls (boules) as close as possible to the small target ball (cochonnet/jack).',
      'Closest team scores 1 point per ball closer than the nearest opponent ball.',
      'First team to 13 points wins.',
    ],
    full: [
      'Teams: 1v1 (3 boules each), 2v2 (3 each), or 3v3 (2 each). Toss the cochonnet (jack) 6–10 metres.',
      'Teams alternate throwing. The team NOT holding (closest to jack) throws until they hold or run out.',
      'POINTING: Throw to get close. SHOOTING: Throw to knock opponent boules away.',
      'END OF ROUND (mène): When all boules are thrown, the team with the closest boule scores.',
      'Score = number of your boules closer to jack than the nearest opponent boule.',
      'First to 13 points wins the game.',
      'If no team reaches 13 after agreed rounds, highest score wins.',
    ],
  },
  'croquet': {
    quickStart: [
      'Hit balls through hoops in the correct order using a mallet.',
      'Score 1 point per hoop cleared. Running a hoop earns a bonus stroke.',
      'Hitting another ball (roquet) earns 2 bonus strokes.',
      'First to complete all hoops and hit the peg wins.',
    ],
    full: [
      'Standard Association Croquet: each side has 2 balls. Complete 12 hoops (6 each direction) + peg in order.',
      'STROKES: Each turn starts with 1 stroke. Running a hoop = 1 bonus stroke. Roqueting (hitting another ball) = 2 bonus strokes.',
      'CROQUET SHOT: After roqueting, place your ball touching theirs. Strike your ball to move both.',
      'CONTINUATION: After a croquet shot you get 1 continuation stroke.',
      'Each ball may be roqueted once per turn (reset after running a hoop).',
      'WINNING: First side to run all hoops and hit the peg with both balls wins.',
      'GARDEN CROQUET: simplified rules — score 1 per hoop run, first to agreed total wins.',
    ],
  },
  'bowling': {
    quickStart: [
      '10 frames. Each frame: roll up to 2 balls to knock down all 10 pins.',
      'Strike (all 10 on first roll): score 10 + next 2 balls\' total.',
      'Spare (all 10 on second roll): score 10 + next ball\'s total.',
      'Open frame: score = pins knocked down.',
      '10th frame: if you get a strike or spare, you get bonus rolls. Maximum score is 300.',
    ],
    full: [
      '10 frames per game. In each frame, roll up to 2 balls.',
      'STRIKE (X): All 10 pins on the first ball. Score = 10 + sum of next 2 deliveries.',
      'SPARE (/): All remaining pins on the second ball. Score = 10 + next 1 delivery.',
      'OPEN FRAME: Neither strike nor spare. Score = pins knocked down.',
      '10TH FRAME: If you roll a strike, you get 2 more rolls. If you roll a spare, you get 1 more roll. Otherwise just 2 rolls.',
      'PERFECT GAME: 12 consecutive strikes = 300 points.',
      'Highest score wins.',
    ],
  },
  'farkle': {
    quickStart: [
      'Roll 6 dice. You must score at least one die or it\'s a Farkle (lose all unbanked points this turn).',

      'Scoring: 1s = 100 pts, 5s = 50 pts, three 1s = 1000, three of any kind = that number × 100 (e.g., three 4s = 400).',
      'After scoring, choose to bank your points or roll remaining dice to add more.',
      'If all 6 dice score, you can roll all 6 again (hot dice).',
      'Must reach 1000 pts in a single turn to open your account. After that, bank at any time.',
      'First to 10 000 wins (everyone else gets one last turn to beat them).',
    ],
    full: [
      'On your turn, roll all 6 dice.',
      'SCORING COMBINATIONS:',
      '  Single 1 = 100 points',
      '  Single 5 = 50 points',
      '  Three 1s = 1000 points',
      '  Three 2s = 200 points',
      '  Three 3s = 300 points',
      '  Three 4s = 400 points',
      '  Three 5s = 500 points',
      '  Three 6s = 600 points',
      '  Four of a kind = double the three-of-a-kind score',
      '  Five of a kind = triple the three-of-a-kind score',
      '  Six of a kind = 3000 points',
      '  Straight 1-2-3-4-5-6 = 1500 points',
      '  Three pairs = 1500 points',
      'FARKLE: If no dice score on a roll, it\'s a Farkle — you lose all unbanked points for that turn.',
      'HOT DICE: If all 6 dice score in a single roll, you may roll all 6 again and add to your total.',
      'BANKING: After scoring dice, you may bank your points (add to total) or continue rolling remaining dice.',
      'OPENING: You must score at least 1000 points in a single turn before you can bank.',
      'WINNING: First to reach 10 000 triggers final round — all other players get one more turn.',
      'Player with highest score (at least 10 000) after final round wins.',
    ],
  },
}

const QUICK_START_NO: Record<string, string[]> = {
  'maxi-yatzy': [
    'Kast 6 terninger opp til 3 ganger per tur — hold terninger mellom kastene.',
    'Skriv inn én kategori per tur. Hver kategori kan bare brukes én gang.',
    'Øvre seksjon (Ettere–Seksere): summer matchende terninger. Bonus 100 p ved sum ≥ 84.',
    'Nedre seksjon: 1 Par, 2 Par, 3 Par, 3/4/5 Like, Rekker, Hytte (2+3), Hus (3+3), Tårn (2+4), Sjanse, Maxi Yatzy (100 p).',
    'Høyeste totalscore vinner.',
  ],
  'yatzy': [
    'Kast 5 terninger opp til 3 ganger per tur — hold terninger mellom kastene.',
    'Skriv inn én kategori per tur. Hver kan bare brukes én gang.',
    'Øvre seksjon (Ettere–Seksere): sum av matchende terninger. Bonus 50 p ved sum ≥ 63.',
    'Nedre seksjon: 1 Par, 2 Par, 3/4 Like, Fullt Hus, Liten/Stor Straight, Sjanse, Yatzy (50 p).',
    'Høyeste totalscore vinner.',
  ],
  'darts-501': [
    'Hver spiller starter med 501 poeng.',
    'Kast 3 piler i tur. Trekk poengsummen fra totalen din.',
    'Du må avslutte på nøyaktig 0 — siste pil må treffe en dobling (eller blink).',
    'Bust (under 0 eller nøyaktig 1): poengsummen tilbakestilles til start av turen.',
    'Første til nøyaktig 0 vinner.',
  ],
  'darts-301': [
    'Hver spiller starter med 301 poeng.',
    'Kast 3 piler i tur. Trekk poengsummen fra totalen din.',
    'Du må avslutte på nøyaktig 0 — siste pil må treffe en dobling (eller blink).',
    'Bust (under 0 eller nøyaktig 1): poengsummen tilbakestilles.',
    'Første til nøyaktig 0 vinner.',
  ],
  'darts-cricket': [
    'Tall i spill: 15, 16, 17, 18, 19, 20 og Blink.',
    'Treff et tall 3 ganger for å "lukke" det. Merker: 1 = /, 2 = X, 3 = lukket (⊗).',
    'Etter lukking scorer ekstra treff poeng — men bare hvis motstanderen ikke har lukket tallet ennå.',
    'Vinn ved å lukke alle tall OG ha høyest (eller lik) score.',
  ],
  'hearts': [
    '3–6 spillere, standard 52-korts kortstokk.',
    'Hvert stikk: høyeste kort av ledet farge vinner. Hjerter er ikke trumf.',
    'Poeng: Hjerter = 10 p hvert (Hjerteess = 20 p), Spardam = 100 p, Ruterknekt = −100 p.',
    'Skyt månen (valgfritt): ta ALLE hjerter + Spardam → du scorer 0, alle andre får 240 p.',
    'Spillet slutter når noen når 500 poeng. Lavest score vinner.',
  ],
  'farkle': [
    'Kast 6 terninger. Du MÅ score minst én terning, ellers er det Farkle (tap alle ubankede poeng).',
    'Poeng: 1 = 100 p, 5 = 50 p, tre ettere = 1000, tre like = antall × 100 (f.eks. tre femmere = 500).',
    'Etter scoring: bank poengene eller kast gjenstående terninger for å samle mer.',
    'Alle 6 terninger scorer: hot dice — kast alle 6 igjen og legg til.',
    'Trenger 1000 p i én tur for å åpne kontoen. Første til 10 000 vinner (alle andre får én siste tur).',
  ],
  'spades': [
    '4 spillere, 2 lag. Spar er alltid trumf.',
    'Alle byr på antall stikk de forventer. Laget scorer 10 p per budt stikk ved å nå budet.',
    'Overtrekk (poser) gir 1 p, men 10 poser = −100 p. Underbuding koster 10 p per stikk under.',
    'Første lag til 500 p vinner.',
  ],
  'rummy': [
    'Trekk et kort, kast ett. Mål: form grupper (3+ like rang) og rekker (3+ påfølgende, samme farge).',
    'Gå ut ved å legge ned alle kortene dine.',
    'Straffepoeng lik kortverdi av ulagte kort i motstandernes hender.',
    'Bildekort = 10 p, ess = 1 p. Lavest score vinner.',
  ],
  'gin-rummy': [
    '2 spillere. Trekk og kast ett kort per tur. Form grupper og rekker.',
    'Bank når gjenstående ubrukte kort summerer til 10 eller mindre.',
    'Motstanderen legger av på dine kombinasjoner, teller gjenstående.',
    'Gin (0 ubrukte): +25 bonuspoeng. Underkutt (motstanderens gjenstående ≤ din): +25 p til motstanderen.',
    'Høyest score etter avtalte runder vinner.',
  ],
  'canasta': [
    '2–6 spillere (best med 4 i 2 lag). Form kortkombinasjoner av 3+ kort med samme rang.',
    'En canasta er en kombinasjon på 7+ kort. Naturlig canasta = 7 uten jokere (+500 p).',
    'Jokere og 2-ere kan erstatte kort, men ikke overskride naturlige kort i kombinasjonen.',
    'Første lag til 5000 p vinner.',
  ],
  'phase-10': [
    'Fullfør 10 spesifikke faser i rekkefølge. Trekk et kort, kast ett.',
    'Faser: grupper (like rang) og rekker (påfølgende). Eks. fase 1: 2 grupper à 3 kort.',
    'Jokere kan erstatte alle kort. Skip-kort gjør at neste spiller mister en tur.',
    'Straffepoeng for gjenværende kort etter at noen går ut. Lavest score vinner.',
  ],
  'uno': [
    'Match topkortet etter farge, tall eller symbol.',
    'Trekk 2 hvis du ikke kan spille. Ropa "UNO!" med 1 kort igjen.',
    'Spesialkort: Hopp, Snu, Trekk 2, Wild, Wild Trekk 4.',
    'Når noen går ut, scorer andre straffepoeng. Første til 500 avslutter spillet — lavest score vinner.',
  ],
  'cabo': [
    '4 kort ned. Kikk på dine to nederste i starten.',
    'Trekk et kort og bytt det mot et av dine (kast gammel), eller kast det (bruk spesialeffekt).',
    'Ropa "Cabo" når du tror håndsummen er lavest. Alle andre får én tur til.',
    'Lavest håndsum vinner runden. Første til 100 p er ute — lavest score til slutt vinner.',
  ],
  'cribbage': [
    '2–4 spillere. Del 6 kort; alle kaster 2 til "kribben" (tilhører utdeleren).',
    'Vend et startkort. Er det en knekt, scorer utdeleren 2 poeng.',
    'Spill kort om hverandre og score for 15-ere, par, rekker og 31-ere. Deretter telles håndene.',
    'Første til 121 poeng vinner.',
  ],
  'doppelkopf': [
    '4 spillere, 2 lag (Re mot Kontra). Lag holdes hemmelig — avsløres av hvem som holder kloverkonginnene.',
    'Mål: ta stikk verdt 120+ poeng (Re) eller stoppe dem (Kontra).',
    'Vinnerlaget scorer 1 spillpoeng per spiller; bonuser for ekstra prestasjoner.',
  ],
  'skat': [
    '3 spillere. Del 10 kort med 2 skjulte (skaten).',
    'Spillerne byr for å bli deklaranten — tar opp skaten og velger trumf.',
    'Deklaranten forsøker å vinne kortpoeng; forsvarerne forsøker å stoppe dem.',
  ],
  'catan': [
    'Samle ressurser (Tre, Leire, Korn, Sau, Malm) for å bygge veier, bosetninger, byer og kort.',
    'Bosetninger = 1 sp, Byer = 2 sp. Lengste vei og Største hær = 2 sp hver.',
    'Første til 10 seierpoeng vinner.',
  ],
  'ticket-to-ride': [
    'Krev jernbaneruter ved å spille matchende fargede togsett.',
    'Score poeng for krevde ruter. Fullfør destinasjonskort (bonus) eller mislykkes (minus).',
    'Når en spiller har ≤2 togsett igjen, alle får én tur til — deretter telles score.',
  ],
  'carcassonne': [
    'Legg fliser etter tur for å bygge et middelaldersk landskap av byer, veier og klostre.',
    'Plasser en brikke på flisen for å kreve en funksjon. Score når funksjoner fullføres.',
    'Ved slutten: score ufullstendige funksjoner og jordbruksområder.',
  ],
  'scrabble': [
    'Legg bokstavbrikker for å forme ord. Ord må kobles til eksisterende brikker.',
    'Score = sum av bokstavverdier. Dobbelt/trippelt-felt multipliserer score.',
    'Bingo (alle 7 brikker i ett trekk): +50 p. Trekk fra ubrukte brikker til slutt.',
    'Høyest score vinner.',
  ],
  'backgammon': [
    'Flytt alle 15 brikker rundt brettet inn i hjemme-bordet ditt, deretter bær dem av.',
    'Kast 2 terninger per tur; flytt brikker de viste tallene.',
    'Treff en enkelt motstanderbrikke: send den til bar — den må inn igjen før andre trekk.',
    'Første til å bære av alle brikker vinner.',
  ],
  'sequence': [
    '2–12 spillere i lag. Spill et kort og plasser en brikke på matchende brett-felt.',
    'Form en sekvens på 5 brikker på rad (horisontalt, vertikalt eller diagonalt).',
    'Knekter: én øye = fjern motstanderbrikke; to øyne = joker (spill hvor som helst).',
    'Første lag til nødvendig antall sekvenser vinner.',
  ],
  'petanque': [
    'Lag kaster kuler (boules) så nær målkulen (cochonnet) som mulig.',
    'Nærmeste lag scorer 1 poeng per kule nærmere enn motstanderens nærmeste kule.',
    'Første lag til 13 poeng vinner.',
  ],
  'bowling': [
    '10 frames. Hvert frame: kast opp til 2 ganger for å velte alle 10 kjegler.',
    'Strike (alle 10 på første kast): score 10 + neste 2 kast.',
    'Spare (alle 10 på andre kast): score 10 + neste kast.',
    'Åpent frame: score = veltede kjegler. Maks totalscore er 300.',
  ],
  'croquet': [
    'Slå baller gjennom ringer i riktig rekkefølge med en kølle.',
    'Score 1 poeng per ring passert. Å passere en ring gir et bonusslag.',
    'Treffe en annens ball (roquet) gir 2 bonusslag.',
    'Første til å fullføre alle ringer og treffe pelen vinner.',
  ],
}

export function getRules(gameId: string, locale: string): GameRules | undefined {
  const rules = RULES[gameId]
  if (!rules) return undefined
  const noQS = locale === 'no' ? QUICK_START_NO[gameId] : undefined
  if (noQS) return { ...rules, quickStart: noQS }
  return rules
}
