export interface GameRules {
  quickStart: string[]
  full: string[]
}

export const RULES: Record<string, GameRules> = {
  'maxi-yatzy': {
    quickStart: [
      'Roll 6 dice up to 3 times per turn, keeping any dice between rolls.',
      'Score in any empty category — each category can only be used once.',
      'Upper section (Ones–Sixes): score matching dice. Bonus of 100 pts if sum ≥ 84.',
      'Lower section: 1 Pair, 2 Pair, 3 Pair, 3/4/5 of a Kind, Straights, House, Hus, Tårn, Sjanse, Maxi Yatzy (100 pts).',
      'Highest total score wins.',
    ],
    full: [
      'Each player takes turns rolling all 6 dice.',
      'After each roll you may set aside any dice and re-roll the rest — up to 3 rolls total.',
      'After your final roll, choose one unfilled category to score in.',
      'UPPER SECTION: Ones through Sixes — total the matching dice. Score 100 bonus if upper sum ≥ 84.',
      'LOWER SECTION:',
      '  1 Par: sum of highest pair',
      '  2 Par: sum of two pairs',
      '  3 Par: sum of three pairs',
      '  3 Like: sum of three matching dice',
      '  4 Like: sum of four matching dice',
      '  5 Like: sum of five matching dice',
      '  Liten Straight (1-2-3-4-5): 15 points',
      '  Stor Straight (2-3-4-5-6): 20 points',
      '  Full Straight (1-2-3-4-5-6): 21 points',
      '  Hytte (2+3 of a kind): sum of all dice',
      '  Hus (3+3 of a kind): sum of all dice',
      '  Tårn (2+4 of a kind): sum of all dice',
      '  Sjanse: sum of all dice',
      '  Maxi Yatzy (all 6 same): 100 points',
      'If you cannot or do not want to score a category, you must cross it out (score 0).',
      'Game ends when all players have filled every category. Highest total wins.',
    ],
  },
  'yatzy': {
    quickStart: [
      'Roll 5 dice up to 3 times per turn, keeping any dice between rolls.',
      'Score in any empty category — each can only be used once.',
      'Upper section (Ones–Sixes): score matching dice. Bonus of 50 pts if sum ≥ 63.',
      'Lower section: 1 Pair, 2 Pair, 3/4 of a Kind, Full House, Small/Large Straight, Chance, Yatzy (50 pts).',
      'Highest total wins.',
    ],
    full: [
      'Roll 5 dice up to 3 times per turn.',
      'After each roll you may keep any dice and re-roll the rest.',
      'Score in one unfilled category after your final roll.',
      'UPPER SECTION (Ones–Sixes): Score the total of all matching dice. 50 bonus points if upper section total ≥ 63.',
      'LOWER SECTION:',
      '  1 Pair: sum of highest pair',
      '  2 Pair: sum of two pairs',
      '  3 of a Kind: sum of three matching dice',
      '  4 of a Kind: sum of four matching dice',
      '  Full House (2+3): 25 points',
      '  Small Straight (1-2-3-4 or 2-3-4-5): 30 points',
      '  Large Straight (1-2-3-4-5 or 2-3-4-5-6): 40 points',
      '  Chance: sum of all 5 dice',
      '  Yatzy (all 5 same): 50 points',
      'Cross out any category you cannot or choose not to score (0 points).',
      'Game ends when all categories are filled. Highest total wins.',
    ],
  },
  'darts-501': {
    quickStart: [
      'Each player starts with 501 points.',
      'Take turns throwing 3 darts each. Subtract your score from your total.',
      'You must finish on exactly 0 — the finishing dart must land in a double (or bullseye).',
      'If you go below 0, or land exactly on 1, your turn is a "bust" — your score resets to what it was before your throw.',
      'First player to reach exactly 0 wins.',
    ],
    full: [
      'Each player begins with 501 points.',
      'Players alternate turns throwing 3 darts at the board.',
      'Score is the total of the 3 darts, subtracted from your current score.',
      'Doubles: doubles ring scores double the segment value.',
      'Trebles: treble ring scores triple the segment value.',
      'Bull: outer bull = 25, inner bull (bullseye) = 50.',
      'CHECKOUT: To win, you must reduce your score to exactly 0.',
      '  The final dart must land in a double or the bullseye.',
      '  If you cannot checkout or overshoot, your turn is a "bust" — score returns to start of that turn.',
      '  If your score reaches 1, it is a bust (cannot check out on 1).',
      'First player to reach exactly 0 wins.',
    ],
  },
  'hearts': {
    quickStart: [
      '3–6 players, standard 52-card deck (remove low cards to make it divide evenly).',
      'Each trick: highest card of the led suit wins — unless trumped. Hearts have no trump.',
      'Hearts = 1 penalty point each. Queen of Spades = 13 penalty points.',
      'Shooting the moon: if one player takes ALL hearts + Queen of Spades, they score 0 and all others get 26 points.',
      'Game ends when someone reaches 100 points. Lowest score wins.',
    ],
    full: [
      'Deal all cards evenly. Players pass 3 cards to the left before each round (direction rotates).',
      'The player with the 2 of Clubs leads the first trick.',
      'Players must follow suit if they can. If unable, play any card.',
      'The highest card of the led suit wins the trick. The winner leads next.',
      'Hearts cannot be led until a heart has been "broken" (played when unable to follow suit).',
      'SCORING PER ROUND:',
      '  Each heart taken = 1 penalty point',
      '  Queen of Spades = 13 penalty points',
      '  All other cards = 0',
      'SHOOTING THE MOON:',
      '  If one player takes ALL 13 hearts AND the Queen of Spades:',
      '  That player scores 0 for the round, all other players receive 26 points.',
      'Record running totals after each round.',
      'GAME END: The game ends after the round in which a player reaches or exceeds 100 points.',
      'The player with the LOWEST total score wins.',
    ],
  },
  'farkle': {
    quickStart: [
      'Roll 6 dice. You must score at least one die or it\'s a Farkle (lose all unbanked points this turn).',
      'Scoring: 1s = 100 pts, 5s = 50 pts, three 1s = 1000, three of any kind = that number × 100 (e.g., three 4s = 400).',
      'After scoring, choose to bank your points or roll remaining dice to add more.',
      'If all 6 dice score, you can roll all 6 again (hot dice).',
      'Must reach 1000 pts in a single turn to open your account. After that, bank at any time.',
      'First to 10 000 wins (everyone else gets one last turn to beat them).',
    ],
    full: [
      'On your turn, roll all 6 dice.',
      'SCORING COMBINATIONS:',
      '  Single 1 = 100 points',
      '  Single 5 = 50 points',
      '  Three 1s = 1000 points',
      '  Three 2s = 200 points',
      '  Three 3s = 300 points',
      '  Three 4s = 400 points',
      '  Three 5s = 500 points',
      '  Three 6s = 600 points',
      '  Four of a kind = double the three-of-a-kind score',
      '  Five of a kind = triple the three-of-a-kind score',
      '  Six of a kind = 3000 points',
      '  Straight 1-2-3-4-5-6 = 1500 points',
      '  Three pairs = 1500 points',
      'FARKLE: If no dice score on a roll, it\'s a Farkle — you lose all unbanked points for that turn.',
      'HOT DICE: If all 6 dice score in a single roll, you may roll all 6 again and add to your total.',
      'BANKING: After scoring dice, you may bank your points (add to total) or continue rolling remaining dice.',
      'OPENING: You must score at least 1000 points in a single turn before you can bank.',
      'WINNING: First to reach 10 000 triggers final round — all other players get one more turn.',
      'Player with highest score (at least 10 000) after final round wins.',
    ],
  },
}
